from app.main import app
from app import question_assets  # noqa: F401,E402
from app import practice  # noqa: F401,E402
from app import admin_workflow  # noqa: F401,E402
from app import question_bank  # noqa: F401,E402
from app import question_catalog_api  # noqa: F401,E402
from app import quiz_builder  # noqa: F401,E402
from app import quality_gate_patch  # noqa: F401,E402
from app import parent_notifications  # noqa: F401,E402
from app import student_session_api  # noqa: F401,E402
from app import security_hardening  # noqa: F401,E402
from app import student_quiz  # noqa: F401,E402
from app import student_admin  # noqa: F401,E402
from app import admin_dashboard  # noqa: F401,E402
from app import student_reports  # noqa: F401,E402
from app import student_review_exports  # noqa: F401,E402
from app import academic  # noqa: F401,E402
from app import academic_admin  # noqa: F401,E402
from app import knowledge_map  # noqa: F401,E402
from app import analytics  # noqa: F401,E402
from app import adaptive_practice  # noqa: F401,E402
from app import student_portal  # noqa: F401,E402
from app import student_command_center  # noqa: F401,E402
from app import progress_dashboard  # noqa: F401,E402
from app import teacher_intervention_queue  # noqa: F401,E402
from app import teacher_intervention_cases  # noqa: F401,E402
from app import teacher_intervention_ui  # noqa: F401,E402
from app import system_readiness  # noqa: F401,E402
from app import operations_readiness  # noqa: F401,E402
from app import technical_observability  # noqa: F401,E402
from app import database_performance  # noqa: F401,E402
from app import runtime_health  # noqa: F401,E402
from app import runtime_probe  # noqa: F401,E402
from app import release_bootstrap_api  # noqa: F401,E402
from app import phase2_admin  # noqa: F401,E402
from app import admin_auth  # noqa: F401,E402
from app import system_diagnostics  # noqa: F401,E402
from app import document_recovery  # noqa: F401,E402
from app import whatsapp_webhook  # noqa: F401,E402
from app import whatsapp_monitor  # noqa: F401,E402
from app import alert_center  # noqa: F401,E402
from app import question_bank_quality  # noqa: F401,E402
from app import question_bank_balance  # noqa: F401,E402
from app import quiz_lifecycle  # noqa: F401,E402
from app import student_lesson  # noqa: F401,E402
from app import lesson_sources  # noqa: F401,E402
from app import source_review  # noqa: F401,E402
from app import current_corpus_ops  # noqa: F401,E402
from app import source_asset_admin  # noqa: F401,E402
from app import advanced_learning  # noqa: F401,E402
from app import exam_blueprint  # noqa: F401,E402
from app import exam_engine  # noqa: F401,E402
from app import exam_diagnostics  # noqa: F401,E402
from app import exam_advanced_analytics  # noqa: F401,E402
from app import study_intelligence  # noqa: F401,E402
from app.corpus_public_status import router as corpus_public_status_router

# Register explicit APIRouters before importing legacy side-effect route modules.
# FastAPI's include_router() flattens APIRoutes into app.routes when invoked here.
app.include_router(corpus_public_status_router)
from app import research_engine  # noqa: F401,E402
from app import ai_operations  # noqa: F401,E402
from app import ai_budget_guard  # noqa: F401,E402
from app import file_search_store  # noqa: F401,E402
from app import source_indexing  # noqa: F401,E402
from app import research_admin_ops  # noqa: F401,E402
from app import science_lesson_studio  # noqa: F401,E402
from app import science_reference_library  # noqa: F401,E402
from app import science_reference_ui  # noqa: F401,E402
from app import science_reference_curriculum_map  # noqa: F401,E402
from app import lesson_studio_reference_review  # noqa: F401,E402
from app import lesson_studio_reference_workspace  # noqa: F401,E402
from app import lesson_studio_preprocess_runtime  # noqa: F401,E402
from app import lesson_studio_diagram_router_runtime  # noqa: F401,E402
from app import lesson_studio_notation_runtime  # noqa: F401,E402
from app import lesson_studio_pdf_runtime  # noqa: F401,E402
from app import lesson_studio_review  # noqa: F401,E402
from app import lesson_studio_content_review  # noqa: F401,E402
from app import lesson_studio_source_editor  # noqa: F401,E402
from app import lesson_studio_source_editor_ui  # noqa: F401,E402
from app import lesson_studio_workspace  # noqa: F401,E402
from app import lesson_studio_diagram_spec_history  # noqa: F401,E402
from app import lesson_studio_workspace_diagram_editor  # noqa: F401,E402
from app import lesson_studio_workspace_concurrency  # noqa: F401,E402
from app import lesson_studio_enhancements  # noqa: F401,E402
from app import lesson_studio_second_reviewer  # noqa: F401,E402
from app import lesson_studio_tools_ui  # noqa: F401,E402
from app import lesson_studio_quality  # noqa: F401,E402
from app import lesson_studio_export_presets  # noqa: F401,E402
from app import lesson_studio_acceptance  # noqa: F401,E402
from app import lesson_studio_version_history  # noqa: F401,E402
from app import lesson_studio_version_diff  # noqa: F401,E402
from app import lesson_studio_change_impact  # noqa: F401,E402
from app import lesson_studio_approval_state  # noqa: F401,E402
from app import lesson_studio_release_readiness  # noqa: F401,E402
from app import content_completion  # noqa: F401,E402
from app import completion_audit  # noqa: F401,E402
from app import e2e_content_acceptance  # noqa: F401,E402
from app import acceptance_work_queue  # noqa: F401,E402
from app import visual_review_assistant  # noqa: F401,E402
from app import visual_review_triage  # noqa: F401,E402
from app import project_closure  # noqa: F401,E402
from app import lesson_studio_handwriting_pipeline  # noqa: F401,E402
from app import lesson_studio_visual_summary  # noqa: F401,E402
from app import external_creative_integrations  # noqa: F401,E402
from app import canva_oauth  # noqa: F401,E402
from app import canva_diagnostics  # noqa: F401,E402
from app import lesson_studio_external_artifacts  # noqa: F401,E402
from app import lesson_studio_integrations_ui  # noqa: F401,E402
from app import release_hardening  # noqa: F401,E402
from app import lesson_pack_studio  # noqa: F401,E402
from app import lesson_pack_review_settings  # noqa: F401,E402
from app import lesson_pack_studio_ui  # noqa: F401,E402
from app import lesson_pack_student_handout_runtime  # noqa: F401,E402
from app import lesson_pack_export_readiness_ui  # noqa: F401,E402
from app import lesson_presentation_studio  # noqa: F401,E402
from app import lesson_presentation_studio_ui  # noqa: F401,E402
from app import lesson_presentation_editor_productivity  # noqa: F401,E402
from app import lesson_presentation_editor_productivity_ui  # noqa: F401,E402
from app import lesson_presentation_advanced_design  # noqa: F401,E402
from app import lesson_presentation_advanced_design_ui  # noqa: F401,E402
from app import lesson_presentation_layout_toolkit_ui  # noqa: F401,E402
from app import lesson_presentation_pro_editor_ui  # noqa: F401,E402
from app import lesson_presentation_revision_history  # noqa: F401,E402
from app import lesson_presentation_revision_history_ui  # noqa: F401,E402
from app import source_cleanup_studio  # noqa: F401,E402
from app import source_cleanup_studio_ui  # noqa: F401,E402
from app import lesson_presentation_approval_ledger  # noqa: F401,E402
from app import lesson_presentation_approval_ledger_ui  # noqa: F401,E402

from app import content_maintenance_api  # noqa: F401,E402
from app import feature_status  # noqa: F401,E402
