from fastapi.responses import HTMLResponse
from .main import app

PAGE=r'''<!doctype html><html lang="ar" dir="rtl"><meta name="viewport" content="width=device-width,initial-scale=1"><title>الهيكل الأكاديمي</title><style>
body{font-family:system-ui;background:#f5f7fb;margin:0;color:#172033}main{max-width:1100px;margin:auto;padding:18px}.box{background:#fff;padding:15px;border-radius:16px;margin:12px 0;box-shadow:0 3px 14px #0001}.row{display:flex;gap:8px;flex-wrap:wrap}select,input,button{padding:10px;border:1px solid #ccd2dd;border-radius:9px;font:inherit}table{width:100%;border-collapse:collapse}td,th{padding:8px;border-bottom:1px solid #eee;text-align:right}.muted{color:#667085;font-size:13px}</style><main>
<h1>الهيكل الأكاديمي متعدد المواد</h1>
<div class="box row"><a href="/admin/dashboard">لوحة التحكم</a><a href="/admin/login">جلسة الإدارة</a></div>
<div class=box><h2>إنشاء إصدار منهج</h2><div class=row><select id=subj></select><select id=grade></select><input id=year value="2026/2027"><button onclick=createCurriculum()>إنشاء المنهج والترمين</button></div><div id=msg class=muted></div></div>
<div class=box><h2>إضافة الوحدات والدروس</h2><div class=row><select id=currSel onchange=fillTerms()></select><select id=termSel onchange=fillUnits()></select><input id=unitTitle placeholder="اسم الوحدة"><button onclick=addUnit()>إضافة وحدة</button></div><div class=row style="margin-top:8px"><select id=unitSel></select><input id=lessonTitle placeholder="اسم الدرس"><input id=chapter placeholder="الفصل/الباب (اختياري)"><button onclick=addLesson()>إضافة درس</button></div><div id=structureMsg class=muted></div></div>
<div class=box><h2>إضافة مفاهيم الدرس</h2><div class=row><select id=conceptLesson></select><input id=conceptTitle placeholder="اسم المفهوم"><button onclick=addConcept()>إضافة مفهوم</button></div><div id=conceptMsg class=muted></div></div>
<div class=box><h2>المهارات المعتمدة</h2><div id=skillsBox class=muted>جارٍ التحميل...</div></div>
<div class=box><h2>ربط ملفات PDF المرفوعة بالمنهج</h2><p class=muted>للملفات القديمة التي رُفعت قبل إضافة التصنيف الأكاديمي.</p><div id=docContext></div></div>
<div class=box><h2>المناهج</h2><div id=curricula></div></div>
<div class=box><h2>تغطية المنهج</h2><button onclick=coverage()>تحديث</button><div id=cov></div></div>
<script>
const H=()=>({});
function e(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
async function jf(u,o={}){let r=await fetch(u,o),x=await r.json();if(!r.ok)throw new Error(typeof x.detail==='string'?x.detail:JSON.stringify(x.detail));return x}
let catalog=null,docsData=[];async function load(){try{let x=await jf('/api/academic/catalog');catalog=x;docsData=await jf('/api/documents');subj.innerHTML=x.subjects.map(s=>`<option value="${s.id}">${e(s.name_ar)}</option>`).join('');grade.innerHTML=x.grades.map(g=>`<option value="${g.id}">${e(g.name_ar)}</option>`).join('');let ls=await jf('/api/lessons');conceptLesson.innerHTML=ls.map(l=>`<option value="${l.id}">${e(l.title)}</option>`).join('');let sk=await jf('/api/academic/skills');skillsBox.innerHTML=sk.map(s=>`<span style="display:inline-block;padding:7px 10px;margin:4px;border:1px solid #ddd;border-radius:20px">${e(s.name_ar)}</span>`).join('');currSel.innerHTML=x.curricula.map(c=>`<option value="${c.id}">${e(c.subject_name)} · ${e(c.grade_name)} · ${e(c.academic_year)}</option>`).join('');fillTerms();renderDocContext();curricula.innerHTML=x.curricula.length?'<table><tr><th>المادة</th><th>الصف</th><th>السنة</th><th>الإصدار</th></tr>'+x.curricula.map(c=>`<tr><td>${e(c.subject_name)}</td><td>${e(c.grade_name)}</td><td>${e(c.academic_year)}</td><td>${e(c.version_label)}</td></tr>`).join('')+'</table>':'لا توجد مناهج بعد';coverage()}catch(err){msg.textContent=err.message}}
function renderDocContext(){if(!docsData.length){docContext.innerHTML='<div class=muted>لا توجد ملفات مرفوعة.</div>';return}let un=docsData.filter(d=>!d.curriculum_version_id||!d.term_id||!d.subject_id||!d.grade_level_id);if(!un.length){docContext.innerHTML='<div style="color:#067647">✅ كل الملفات مرتبطة بسياق أكاديمي.</div>';return}docContext.innerHTML=un.map(d=>`<div style="padding:10px;border-bottom:1px solid #eee"><b>#${d.id} ${e(d.filename)}</b><div class=row style="margin-top:8px"><select id="ds${d.id}" onchange="docCv(${d.id})">${catalog.subjects.map(s=>`<option value="${s.id}">${e(s.name_ar)}</option>`).join('')}</select><select id="dg${d.id}" onchange="docCv(${d.id})">${catalog.grades.map(g=>`<option value="${g.id}">${e(g.name_ar)}</option>`).join('')}</select><select id="dc${d.id}" onchange="docTerms(${d.id})"></select><select id="dt${d.id}"></select><button onclick="saveDocContext(${d.id})">ربط الملف</button></div><div id="dm${d.id}" class=muted></div></div>`).join('');un.forEach(d=>docCv(d.id))}function docCv(id){let s=document.getElementById('ds'+id).value,g=document.getElementById('dg'+id).value,cv=document.getElementById('dc'+id);let rows=catalog.curricula.filter(x=>x.subject_id==s&&x.grade_level_id==g);cv.innerHTML=rows.map(x=>`<option value="${x.id}">${e(x.academic_year)} · ${e(x.version_label)}</option>`).join('');docTerms(id)}function docTerms(id){let cv=document.getElementById('dc'+id),t=document.getElementById('dt'+id);let rows=catalog.terms.filter(x=>x.curriculum_version_id==cv.value);t.innerHTML=rows.map(x=>`<option value="${x.id}">${e(x.name_ar)}</option>`).join('')}async function saveDocContext(id){try{let s=Number(document.getElementById('ds'+id).value),g=Number(document.getElementById('dg'+id).value),cv=Number(document.getElementById('dc'+id).value),t=Number(document.getElementById('dt'+id).value);if(!s||!g||!cv||!t)throw new Error('أنشئ المنهج والترم أولًا ثم اخترهما');await jf('/api/documents/'+id+'/academic-context',{method:'PATCH',headers:{...H(),'Content-Type':'application/json'},body:JSON.stringify({subject_id:s,grade_level_id:g,curriculum_version_id:cv,term_id:t})});document.getElementById('dm'+id).textContent='تم ربط الملف بنجاح';await load()}catch(err){document.getElementById('dm'+id).textContent=err.message}}
async function createCurriculum(){try{let x=await jf('/api/academic/curricula',{method:'POST',headers:{...H(),'Content-Type':'application/json'},body:JSON.stringify({subject_id:Number(subj.value),grade_level_id:Number(grade.value),academic_year:year.value,version_label:'official'})});for(let n of [1,2])await jf('/api/academic/terms',{method:'POST',headers:{...H(),'Content-Type':'application/json'},body:JSON.stringify({curriculum_version_id:x.id,term_number:n,name_ar:n===1?'الترم الأول':'الترم الثاني'})});msg.textContent='تم إنشاء المنهج والترمين';load()}catch(err){msg.textContent=err.message}}
function fillTerms(){if(!catalog)return;let rows=catalog.terms.filter(t=>t.curriculum_version_id==currSel.value);termSel.innerHTML=rows.map(t=>`<option value="${t.id}">${e(t.name_ar)}</option>`).join('');fillUnits()}function fillUnits(){if(!catalog)return;let rows=catalog.units.filter(u=>u.term_id==termSel.value);unitSel.innerHTML=rows.map(u=>`<option value="${u.id}">${e(u.title)}</option>`).join('')}async function addUnit(){try{if(!termSel.value||!unitTitle.value.trim())throw new Error('اختر الترم واكتب اسم الوحدة');await jf('/api/academic/units',{method:'POST',headers:{...H(),'Content-Type':'application/json'},body:JSON.stringify({term_id:Number(termSel.value),title:unitTitle.value,sort_order:(catalog.units.filter(u=>u.term_id==termSel.value).length+1)*10})});unitTitle.value='';structureMsg.textContent='تمت إضافة الوحدة';await load()}catch(err){structureMsg.textContent=err.message}}async function addLesson(){try{if(!unitSel.value||!lessonTitle.value.trim())throw new Error('اختر الوحدة واكتب اسم الدرس');await jf('/api/academic/lessons',{method:'POST',headers:{...H(),'Content-Type':'application/json'},body:JSON.stringify({unit_id:Number(unitSel.value),title:lessonTitle.value,chapter:chapter.value||null,sort_order:10})});lessonTitle.value='';chapter.value='';structureMsg.textContent='تمت إضافة الدرس';await coverage()}catch(err){structureMsg.textContent=err.message}}async function addConcept(){try{if(!conceptLesson.value||!conceptTitle.value.trim())throw new Error('اختر الدرس واكتب اسم المفهوم');await jf('/api/academic/concepts',{method:'POST',headers:{...H(),'Content-Type':'application/json'},body:JSON.stringify({lesson_id:Number(conceptLesson.value),title:conceptTitle.value,sort_order:10})});conceptMsg.textContent='تمت إضافة المفهوم';conceptTitle.value=''}catch(err){conceptMsg.textContent=err.message}}async function coverage(){try{let x=await jf('/api/academic/coverage',{headers:H()});cov.innerHTML=x.length?'<table><tr><th>المادة</th><th>الصف</th><th>الوحدة</th><th>الدرس</th><th>الأسئلة</th><th>المعتمد</th></tr>'+x.map(r=>`<tr><td>${e(r.subject||'غير محدد')}</td><td>${e(r.grade||'غير محدد')}</td><td>${e(r.unit||'—')}</td><td>${e(r.lesson)}</td><td>${r.total_questions}</td><td>${r.approved_questions}</td></tr>`).join('')+'</table>':'لا توجد بيانات مصنفة بعد'}catch(err){cov.textContent=err.message}}load()
</script></main></html>'''
@app.get("/admin/academic",response_class=HTMLResponse)
def academic_admin(): return PAGE
