from __future__ import annotations
from fastapi import Depends
from fastapi.responses import HTMLResponse
from .main import app
from .db import connect
from .security import require_admin

@app.get("/api/admin/dashboard",dependencies=[Depends(require_admin)])
def admin_dashboard_data():
    with connect() as con:
        summary=con.execute("""SELECT
          (SELECT count(*) FROM students) students,
          (SELECT count(*) FROM guardians WHERE active=TRUE) guardians,
          (SELECT count(*) FROM quizzes) quizzes,
          (SELECT count(*) FROM quizzes WHERE published=TRUE) published_quizzes,
          (SELECT count(*) FROM attempts) attempts,
          (SELECT count(*) FROM questions WHERE approved=TRUE) approved_questions,
          (SELECT count(*) FROM parent_notifications WHERE status='queued') queued_notifications,
          (SELECT count(*) FROM parent_notifications WHERE status='failed') failed_notifications,
          (SELECT round(avg(CASE WHEN max_score>0 THEN (score/max_score)*100 END),1) FROM attempts) avg_score,
          (SELECT count(DISTINCT student_id) FROM attempts WHERE completed_at IS NOT NULL) students_with_baseline,
          (SELECT count(*) FROM lesson_source_mappings lsm JOIN documents d ON d.id=lsm.document_id WHERE lsm.approved=TRUE AND d.source_kind IN ('lesson','explanation','textbook','notes')) approved_lesson_sources
        """).fetchone()
        recent=list(con.execute("""SELECT a.id,s.name student_name,q.title quiz_title,a.score,a.max_score,
          round(CASE WHEN a.max_score>0 THEN (a.score/a.max_score)*100 ELSE 0 END,1) percentage,
          coalesce(a.completed_at,a.submitted_at) completed_at
          FROM attempts a JOIN students s ON s.id=a.student_id LEFT JOIN quizzes q ON q.id=a.quiz_id
          ORDER BY coalesce(a.completed_at,a.submitted_at) DESC LIMIT 15""").fetchall())
        weak=list(con.execute("""SELECT s.id,s.name,
          count(a.id) attempts,
          round(avg(CASE WHEN a.max_score>0 THEN (a.score/a.max_score)*100 END),1) average_percentage,
          (SELECT a2.id FROM attempts a2 WHERE a2.student_id=s.id ORDER BY coalesce(a2.completed_at,a2.submitted_at) DESC LIMIT 1) latest_attempt_id
          FROM students s JOIN attempts a ON a.student_id=s.id
          GROUP BY s.id,s.name HAVING avg(CASE WHEN a.max_score>0 THEN (a.score/a.max_score)*100 END)<60
          ORDER BY average_percentage ASC NULLS LAST LIMIT 10""").fetchall())
        notifications=list(con.execute("""SELECT status,count(*) total FROM parent_notifications GROUP BY status ORDER BY status""").fetchall())
        readiness=list(con.execute("""WITH ranked AS (
          SELECT a.student_id,100.0*a.score/nullif(a.max_score,0) pct,
            row_number() OVER(PARTITION BY a.student_id ORDER BY coalesce(a.completed_at,a.submitted_at) DESC,a.id DESC) rn
          FROM attempts a WHERE a.completed_at IS NOT NULL AND a.max_score>0
        ), agg AS (
          SELECT student_id,avg(pct) FILTER(WHERE rn<=5) recent_avg,count(*) FILTER(WHERE rn<=5) recent_count
          FROM ranked GROUP BY student_id
        )
        SELECT CASE WHEN recent_avg>=85 THEN 'exam_ready' WHEN recent_avg>=70 THEN 'nearly_ready' ELSE 'building' END readiness_level,
          count(*) students
        FROM agg GROUP BY 1 ORDER BY 1""").fetchall())
        return {"summary":summary,"recent_attempts":recent,"students_need_attention":weak,"notification_status":notifications,"readiness_distribution":readiness}

PAGE=r'''<!doctype html><html lang="ar" dir="rtl"><meta name="viewport" content="width=device-width,initial-scale=1"><title>لوحة تحكم منصة العلوم التعليمية</title><style>
:root{--bg:#f5f7fb;--card:#fff;--text:#172033;--muted:#667085;--line:#e6eaf0}*{box-sizing:border-box}body{font-family:system-ui;background:var(--bg);color:var(--text);margin:0}.layout{display:grid;grid-template-columns:230px 1fr;min-height:100vh}.side{background:#111827;color:white;padding:20px;position:sticky;top:0;height:100vh}.side h2{margin-top:0}.side .brand{padding:0 8px 12px;border-bottom:1px solid #ffffff1f;margin-bottom:12px}.nav-group{margin:12px 0}.nav-label{font-size:11px;color:#98a2b3;padding:0 9px 5px;text-transform:uppercase;letter-spacing:.04em}.side a{display:block;color:#dbe5ff;text-decoration:none;padding:9px 10px;border-radius:9px;margin:2px 0;font-size:13px}.side a:hover,.side a:focus-visible{background:#ffffff14;outline:none}.side a.primary-nav{background:#ffffff10;color:#fff;font-weight:700}.main{padding:22px;min-width:0}.top{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.box{background:var(--card);padding:15px;border-radius:16px;margin:12px 0;box-shadow:0 3px 14px #0000000a}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.card{background:#f8fafc;border:1px solid var(--line);border-radius:13px;padding:13px}.card h2{margin:5px 0 0;font-size:28px}.grid{display:grid;grid-template-columns:1.4fr .8fr;gap:12px}table{width:100%;border-collapse:collapse}td,th{padding:9px;border-bottom:1px solid var(--line);text-align:right;font-size:14px}input,button{padding:10px;border:1px solid #ccd2dd;border-radius:9px;font:inherit}.muted{color:var(--muted);font-size:13px}.warn{color:#b54708}.bad{color:#b42318}.ok{color:#067647}.pill{display:inline-block;padding:7px 10px;border-radius:999px;border:1px solid var(--line);margin:3px}@media(max-width:850px){.layout{grid-template-columns:1fr}.side{height:auto;position:static}.grid{grid-template-columns:1fr}.side{height:auto;position:static;display:block;padding:10px}.side .brand{display:none}.side nav{display:flex;overflow:auto;gap:8px;padding-bottom:2px}.nav-group{display:flex;gap:4px;margin:0}.nav-label{display:none}.side a{white-space:nowrap;background:#ffffff0c}.main{padding:14px}}
</style><div class=layout><aside class=side><div class=brand><h2>منصة الفيزياء</h2><div class=muted style="color:#98a2b3">إدارة المحتوى والتعلم</div></div><nav>
<div class=nav-group><div class=nav-label>القيادة</div><a class=primary-nav href="/admin/dashboard">الرئيسية</a><a href="/admin/operations-readiness">جاهزية التشغيل النهائي</a><a href="/api/admin/runtime-health">Runtime Health</a><a href="/admin/technical-observability">Technical Observability</a><a href="/admin/database-performance">Database Performance</a><a href="/admin/ai-operations">AI Operations</a><a href="/admin/ai-budget">AI Budget</a><a href="/admin/interventions">تدخلات المدرس</a><a href="/admin/alerts">مركز التنبيهات</a><a href="/admin/readiness">جاهزية النظام</a></div>
<div class=nav-group><div class=nav-label>المحتوى والمصادر</div><a href="/admin/current-corpus">بنك 2026/2027</a><a href="/admin/workflow">مراجعة الأسئلة</a><a href="/admin/visual-review-triage">Quality Triage المرئي</a><a href="/admin/source-review">مراجعة المصدر المرئي</a><a href="/admin/research-engine">محرك المصادر الذكي</a><a href="/admin/lesson-studio/workspace">Lesson Studio</a><a href="/admin/lesson-pack-studio">Lesson Pack Studio</a><a href="/admin/lesson-studio/integrations">التكاملات</a><a href="/admin/content-completion">اكتمال المحتوى</a></div>
<div class=nav-group><div class=nav-label>الاختبارات والتعلم</div><a href="/admin/bank">بنك الأسئلة</a><a href="/admin/quiz-builder">إنشاء اختبار</a><a href="/admin/exam-engine">تشغيل الامتحانات</a><a href="/admin/quizzes">إدارة الاختبارات</a><a href="/admin/students">الطلاب والاختبارات</a><a href="/admin/progress">متابعة التقدم</a><a href="/admin/question-analytics">تحليلات الأسئلة</a><a href="/student">بوابة الطالب</a><a href="/student/learning-suite">مركز التعلم الذكي</a></div>
<div class=nav-group><div class=nav-label>القبول والجودة</div><a href="/admin/e2e-content-acceptance">قبول المحتوى الشامل</a><a href="/admin/acceptance-work-queue">قائمة أعمال القبول</a><a href="/admin/lesson-studio/acceptance">قبول Lesson Studio</a><a href="/admin/lesson-studio/release-readiness">جاهزية Lesson Studio</a><a href="/admin/completion-audit">تدقيق الاكتمال</a><a href="/admin/project-closure">إغلاق المشروع</a><a href="/admin/diagnostics">سلامة البيانات</a></div>
<div class=nav-group><div class=nav-label>الإدارة</div><a href="/admin/academic">الهيكل الأكاديمي</a><a href="/admin/parents">أولياء الأمور وواتساب</a><a href="/admin/whatsapp-monitor">مراقبة واتساب</a><a href="/admin/document-recovery">استعادة PDF القديمة</a></div>
</nav></aside><main class=main>
<div class="box top"><span id=msg class=muted>جارٍ التحقق من جلسة الإدارة...</span><button onclick=logout()>تسجيل الخروج</button></div>
<h1>لوحة التحكم</h1><div id=runtimeHealth class=box><span class=muted>جارٍ تحميل Runtime Health...</span></div><div id=dbPerformance class=box><span class=muted>جارٍ تحميل Database Performance...</span></div><div id=alertSummary class=box></div><div class=box><h2>AI & Content Operations</h2><div id=aiSummary class=muted>جارٍ تحميل توزيع النماذج...</div><div class=top style="margin-top:10px"><a class=pill href="/admin/operations-readiness">جاهزية التشغيل النهائي</a><a class=pill href="/admin/technical-observability">Technical Observability</a><a class=pill href="/admin/ai-operations">فتح AI Operations</a><a class=pill href="/admin/ai-budget">AI Budget</a><a class=pill href="/admin/interventions">تدخلات المدرس</a><a class=pill href="/admin/e2e-content-acceptance">قبول المحتوى الشامل</a><a class=pill href="/admin/acceptance-work-queue">أعمال القبول المتبقية</a><a class=pill href="/admin/lesson-studio/workspace">Lesson Studio</a><a class=pill href="/admin/lesson-pack-studio">Lesson Pack Studio</a></div></div><div id=cards class=cards></div>
<div class=box><h2>جاهزية الطلاب للتعلم والامتحان</h2><div id=readiness></div><div class=muted>المؤشر الإداري هنا يعتمد على متوسط آخر 5 محاولات فقط كملخص تشغيلي؛ صفحة الطالب تستخدم المؤشر الأكثر تفصيلًا.</div></div>
<div class=grid><div class=box><h2>آخر نتائج الطلاب</h2><div id=recent></div></div><div class=box><h2>طلاب يحتاجون متابعة</h2><div id=weak></div></div></div>
<div class=box><h2>حالة رسائل أولياء الأمور</h2><div id=notif></div></div>
<script>
const H=()=>({});async function logout(){await fetch('/api/admin/logout',{method:'POST'});location.href='/admin/login'}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
async function load(){let ses=await fetch('/api/admin/session').then(r=>r.json());if(!ses.authenticated){location.href='/admin/login';return}msg.textContent='جلسة الإدارة آمنة ومفعلة';let r=await fetch('/api/admin/dashboard',{headers:H()});if(!r.ok){location.href='/admin/login';return}let x=await r.json(),s=x.summary||{};let [ar,ai,rh,dbp]=await Promise.all([fetch('/api/admin/alert-center/summary').then(r=>r.ok?r.json():null).catch(()=>null),fetch('/api/admin/ai-operations/summary').then(r=>r.ok?r.json():null).catch(()=>null),fetch('/api/admin/runtime-health').then(r=>r.ok?r.json():null).catch(()=>null),fetch('/api/admin/database-performance').then(r=>r.ok?r.json():null).catch(()=>null)]);dbPerformance.innerHTML=dbp?('<b class="'+(dbp.state==='healthy'?'ok':dbp.state==='degraded'?'warn':'bad')+'">'+(dbp.state==='healthy'?'✅ ':dbp.state==='degraded'?'⚠️ ':'⛔ ')+'Database '+esc(dbp.state)+'</b> · Connections '+esc(dbp.summary?.connections||0)+'/'+esc(dbp.summary?.max_connections||0)+' · Pressure '+esc(dbp.summary?.connection_pressure_pct||0)+'% · Query stats '+(dbp.summary?.query_stats_available?'ON':'OFF')+' · <a href="/admin/database-performance">التفاصيل</a>'):'<span class=warn>تعذر تحميل Database Performance</span>';runtimeHealth.innerHTML=rh?('<b class="'+(rh.state==='healthy'?'ok':rh.state==='degraded'?'warn':'bad')+'">'+(rh.state==='healthy'?'✅ ':rh.state==='degraded'?'⚠️ ':'⛔ ')+'Runtime '+esc(rh.state)+'</b> · Technical '+(rh.ready_for_technical_handoff?'✅':'⛔')+' · Deployment '+esc(rh.deployment?.drift_state||'unknown')+' · <code>'+esc(rh.deployment?.git_commit_short||'no-sha')+'</code> · Content gates '+esc(rh.content_gate_count||0)+' · <a href="/admin/technical-observability">التفاصيل</a>'):'<span class=warn>تعذر تحميل Runtime Health</span>';aiSummary.innerHTML=ai?('<b class="'+(ai.summary.blocked_tasks?'warn':'ok')+'">'+(ai.summary.blocked_tasks?'⚠️ ':'✅ ')+ai.summary.ready_tasks+' / '+ai.summary.task_count+' مهام جاهزة</b> · Gemini '+(ai.providers.gemini.configured?'جاهز':'ينتظر مفتاح')+' · GPT reviewer '+(ai.providers.openai.configured?'جاهز':'ينتظر مفتاح')+' · <a href="/admin/ai-operations">التفاصيل</a>'):'<span class=warn>تعذر تحميل حالة نماذج الذكاء</span>';alertSummary.innerHTML=ar?(ar.total?'<b class="'+(ar.error_count?'bad':'warn')+'">⚠️ '+(ar.error_count+ar.warning_count)+' تنبيه يحتاج مراجعة</b> · <a href="/admin/alerts">فتح مركز التنبيهات</a>':'<span class=ok>✅ لا توجد تنبيهات تشغيلية حالية</span>'):'<span class=muted>تعذر تحميل مركز التنبيهات</span>';cards.innerHTML=[['الطلاب',s.students||0],['لديهم خط أساس',s.students_with_baseline||0],['مصادر شرح معتمدة',s.approved_lesson_sources||0],['الاختبارات المنشورة',s.published_quizzes||0],['المحاولات',s.attempts||0],['الأسئلة المعتمدة',s.approved_questions||0],['متوسط النتائج',(s.avg_score??0)+'%'],['رسائل في الانتظار',s.queued_notifications||0],['رسائل فاشلة',s.failed_notifications||0]].map(([a,b])=>`<div class=card><div class=muted>${a}</div><h2>${b}</h2></div>`).join('');
let labels={exam_ready:'جاهز للامتحان',nearly_ready:'قريب من الجاهزية',building:'يبني المستوى'};readiness.innerHTML=x.readiness_distribution.length?x.readiness_distribution.map(v=>`<span class="pill ${v.readiness_level==='exam_ready'?'ok':v.readiness_level==='building'?'warn':''}">${labels[v.readiness_level]||esc(v.readiness_level)}: <b>${v.students}</b></span>`).join(''):'<span class=muted>لا توجد محاولات مكتملة كافية بعد.</span>';
recent.innerHTML=x.recent_attempts.length?'<table><tr><th>الطالب</th><th>الاختبار</th><th>النتيجة</th><th></th></tr>'+x.recent_attempts.map(a=>`<tr><td>${esc(a.student_name)}</td><td>${esc(a.quiz_title||'—')}</td><td class=${Number(a.percentage)<50?'bad':Number(a.percentage)<70?'warn':'ok'}>${a.percentage}%</td><td><a href="/admin/results/${a.id}">التقرير</a></td></tr>`).join('')+'</table>':'لا توجد نتائج حتى الآن';
weak.innerHTML=x.students_need_attention.length?x.students_need_attention.map(a=>`<div style="padding:8px;border-bottom:1px solid #eee"><b>${esc(a.name)}</b><br><span class=bad>متوسط ${a.average_percentage}%</span> · ${a.attempts} اختبار ${a.latest_attempt_id?'<br><a href="/admin/results/'+a.latest_attempt_id+'">آخر تقرير</a>':''}<br><a href="/admin/interventions">فتح مركز تدخل المدرس</a></div>`).join(''):'لا يوجد طلاب تحت حد المتابعة حاليًا';
notif.innerHTML=x.notification_status.length?x.notification_status.map(n=>`<span class=pill>${esc(n.status)}: <b>${n.total}</b></span>`).join(''):'لا توجد رسائل بعد'}load();
</script></main></div></html>'''
@app.get("/admin/dashboard",response_class=HTMLResponse)
def admin_dashboard_page(): return PAGE