from fastapi.responses import HTMLResponse
from .main import app

WORKFLOW = r'''<!doctype html><html lang="ar" dir="rtl"><meta name="viewport" content="width=device-width,initial-scale=1"><title>مراجعة واعتماد الأسئلة</title><style>
body{font-family:system-ui;background:#f5f7fb;margin:0;color:#172033}main{max-width:1400px;margin:auto;padding:16px}.box{background:#fff;border-radius:16px;padding:14px;margin:10px 0;box-shadow:0 3px 14px #0000000a}.grid{display:grid;grid-template-columns:260px minmax(0,1fr) 360px;gap:12px}.top{display:flex;gap:8px;flex-wrap:wrap;align-items:center}input,select,button,textarea{padding:10px;border:1px solid #ccd2dd;border-radius:9px;font:inherit}textarea{width:100%;box-sizing:border-box;min-height:160px}button{cursor:pointer}.doc,.q{padding:9px;border-bottom:1px solid #eee;cursor:pointer}.active{background:#eef4ff}.muted{color:#667085;font-size:13px}.stage{position:relative;display:inline-block;max-width:100%;touch-action:none}.stage img{display:block;max-width:100%;max-height:72vh}.sel{position:absolute;border:3px solid #175cd3;background:#175cd322;display:none;pointer-events:none}.check{padding:8px 10px;border-radius:10px;background:#f7f8fa;margin:6px 0}.ok{background:#ecfdf3}.warn{background:#fff7ed}.asset{max-width:100%;border-radius:10px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}@media(max-width:950px){.grid{grid-template-columns:1fr}.stage img{max-height:none}}
</style><main><h1>مسار مراجعة السؤال واعتماده</h1><div class="box top"><button onclick="location.href='/admin/login'">جلسة الإدارة</button><a href="/admin">لوحة الإدارة</a><a href="/admin/assets">واجهة القص المنفصلة</a><a href="/practice">معاينة الطالب</a><span id="topMsg"></span></div>
<div class="grid"><div class="box"><h3>المستندات</h3><div id="docs"></div><hr><h3>أسئلة الصفحة</h3><div id="pageQs"></div></div>
<div class="box"><div class="top"><button onclick="movePage(-1)">السابق</button><b id="pageLabel">—</b><button onclick="movePage(1)">التالي</button></div><div id="stage" class="stage"><img id="pageImg"><div id="selBox" class="sel"></div></div><div id="imgMsg" class="muted"></div><details><summary>النص الخام للصفحة</summary><pre id="rawText" style="white-space:pre-wrap;background:#f7f8fa;padding:10px;border-radius:8px"></pre></details></div>
<div class="box"><h3>السؤال</h3><textarea id="qtext" placeholder="انسخ السؤال حرفيًا من المصدر، مع الاختيارات"></textarea><select id="subject"><option value="">اختر المادة</option></select><select id="grade"><option value="">اختر الصف</option></select><select id="curriculum"><option value="">اختر إصدار المنهج</option></select><select id="term"><option value="">اختر الترم</option></select><select id="unit"><option value="">اختر الوحدة</option></select><select id="lesson"><option value="">اختر الباب والدرس</option></select><select id="concept"><option value="">اختر المفهوم الأساسي</option></select><select id="skill"><option value="">اختر المهارة الأساسية</option></select><select id="qtype"><option value="unknown">نوع السؤال: غير مصنف</option><option value="mcq">اختيار من متعدد</option><option value="numeric">مسألة حسابية</option><option value="essay">مقالي</option></select><select id="difficulty"><option value="unclassified">الصعوبة: غير مصنفة</option><option value="easy">سهل</option><option value="medium">متوسط</option><option value="hard">صعب</option></select><div class="actions"><button onclick="saveQuestion()">1) حفظ السؤال</button><button onclick="resetCrop()">مسح التحديد</button><button onclick="saveCrop()">2) حفظ القصاصة</button><button onclick="saveClassification()">3) حفظ التصنيف</button></div><div id="status"></div><h4>القصاصة الحالية</h4><img id="assetImg" class="asset"><div id="assetMeta" class="muted"></div><input id="ans" placeholder="الإجابة المعتمدة - مطلوبة قبل الاعتماد" oninput="renderStatus()"><div class="actions"><button id="approveBtn" onclick="approve()">4) اعتماد السؤال</button><button onclick="unapprove()">إلغاء الاعتماد</button></div><div id="sideMsg"></div></div></div></main><script>
let docsData=[],lessonData=[],catalog=null,skillData=[],pages=[],qs=[],selectedDoc=null,pageIndex=0,selectedQ=null,start=null,crop=null,drag=false;
function h(){return {}}async function ensureAdmin(){let s=await fetch('/api/admin/session').then(r=>r.json());if(!s.authenticated){location.href='/admin/login';throw new Error('Authentication required')}}function saveKey(){location.href='/admin/login'}
async function jfetch(url,opt={}){let r=await fetch(url,opt);let x=null;try{x=await r.json()}catch(e){}if(!r.ok)throw new Error((x&&x.detail)||`HTTP ${r.status}`);return x}
async function blobUrl(url){let r=await fetch(url,{headers:h(),cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return URL.createObjectURL(await r.blob())}
async function loadAll(){try{docsData=await jfetch('/api/documents',{headers:h()});catalog=await jfetch('/api/academic/catalog');skillData=await jfetch('/api/academic/skills');lessonData=await jfetch('/api/lessons');qs=await jfetch('/api/questions?limit=1000',{headers:h()});skill.innerHTML='<option value="">اختر المهارة الأساسية</option>'+skillData.map(x=>`<option value="${x.id}">${x.name_ar}</option>`).join('');subject.innerHTML='<option value="">اختر المادة</option>'+catalog.subjects.map(x=>`<option value="${x.id}">${x.name_ar}</option>`).join('');grade.innerHTML='<option value="">اختر الصف</option>'+catalog.grades.map(x=>`<option value="${x.id}">${x.name_ar}</option>`).join('');curriculum.innerHTML='<option value="">اختر إصدار المنهج</option>'+catalog.curricula.map(x=>`<option value="${x.id}">${x.subject_name} — ${x.grade_name} — ${x.academic_year}</option>`).join('');renderAcademic();subject.onchange=renderAcademic;grade.onchange=renderAcademic;curriculum.onchange=renderAcademic;term.onchange=renderAcademic;unit.onchange=renderAcademic;lesson.onchange=loadConcepts;lesson.innerHTML='<option value="">اختر الباب والدرس</option>'+lessonData.map(x=>`<option value="${x.id}">${x.chapter} — ${x.title}</option>`).join('');docs.innerHTML=docsData.map(d=>`<div class="doc ${d.id==selectedDoc?'active':''}" onclick="pickDoc(${d.id})"><b>#${d.id} ${d.filename}</b><br><span class=muted>${d.page_count||0} صفحة · ${d.question_count||0} سؤال · ${d.status}</span></div>`).join('');if(!selectedDoc&&docsData.length)await pickDoc(docsData[0].id);renderPageQs()}catch(e){topMsg.textContent=e.message}}
async function pickDoc(id){selectedDoc=id;pageIndex=0;selectedQ=null;pages=await jfetch(`/api/documents/${id}/pages`,{headers:h()});await showPage();loadAll()}
async function showPage(){if(!pages.length){pageLabel.textContent='لا توجد صفحات';return}pageIndex=Math.max(0,Math.min(pageIndex,pages.length-1));let p=pages[pageIndex].page_number;pageLabel.textContent=`صفحة ${p} من ${pages.length}`;imgMsg.textContent='جارٍ تحميل الصفحة...';try{if(pageImg.dataset.blob)URL.revokeObjectURL(pageImg.dataset.blob);let u=await blobUrl(`/api/documents/${selectedDoc}/page/${p}/preview`);pageImg.dataset.blob=u;pageImg.src=u;imgMsg.textContent=''}catch(e){imgMsg.textContent='تعذر عرض الصفحة: '+e.message}try{let x=await jfetch(`/api/documents/${selectedDoc}/page/${p}/text`,{headers:h()});rawText.textContent=x.extracted_text||''}catch(e){rawText.textContent='تعذر تحميل النص'}resetForm();renderPageQs()}
function movePage(n){pageIndex+=n;showPage()}
function currentPage(){return pages.length?pages[pageIndex].page_number:null}
function renderPageQs(){let p=currentPage();let arr=qs.filter(x=>x.document_id==selectedDoc&&(x.source_page||x.page)==p);pageQs.innerHTML=arr.length?arr.map(x=>`<div class="q ${selectedQ&&selectedQ.id==x.id?'active':''}" onclick="pickQ(${x.id})">#${x.id} ${x.approved?'✅':'🕓'}<br>${String(x.text_verbatim).slice(0,100)}</div>`).join(''):'لا توجد أسئلة محفوظة بهذه الصفحة'}
function renderAcademic(){let cv=curriculum.value?Number(curriculum.value):null;let ts=cv?catalog.terms.filter(x=>x.curriculum_version_id==cv):catalog.terms;term.innerHTML='<option value="">اختر الترم</option>'+ts.map(x=>`<option value="${x.id}">${x.name_ar}</option>`).join('');let tv=term.value?Number(term.value):null;let us=tv?catalog.units.filter(x=>x.term_id==tv):catalog.units;unit.innerHTML='<option value="">اختر الوحدة</option>'+us.map(x=>`<option value="${x.id}">${x.title}</option>`).join('');let arr=lessonData.filter(x=>(!subject.value||x.subject_id==subject.value)&&(!grade.value||x.grade_level_id==grade.value)&&(!curriculum.value||x.curriculum_version_id==curriculum.value)&&(!term.value||x.term_id==term.value)&&(!unit.value||x.unit_id==unit.value));lesson.innerHTML='<option value="">اختر الباب والدرس</option>'+arr.map(x=>`<option value="${x.id}">${x.chapter} — ${x.title}</option>`).join('')}
function resetForm(){selectedQ=null;qtext.value='';subject.value='';grade.value='';curriculum.value='';term.value='';unit.value='';renderAcademic();lesson.value='';concept.innerHTML='<option value="">اختر المفهوم الأساسي</option>';skill.value='';qtype.value='unknown';difficulty.value='unclassified';ans.value='';assetImg.removeAttribute('src');assetMeta.textContent='';resetCrop();renderStatus()}
async function saveQuestion(){let text=qtext.value;if(!text.trim()){sideMsg.textContent='أدخل نص السؤال أولًا';return}let p=currentPage();try{let x=await jfetch(`/api/documents/${selectedDoc}/questions/manual`,{method:'POST',headers:{...h(),'Content-Type':'application/json'},body:JSON.stringify({page:p,text_verbatim:text,question_type:qtype.value,lesson_id:lesson.value?Number(lesson.value):null,subject_id:subject.value?Number(subject.value):null,grade_level_id:grade.value?Number(grade.value):null,curriculum_version_id:curriculum.value?Number(curriculum.value):null,term_id:term.value?Number(term.value):null,unit_id:unit.value?Number(unit.value):null,difficulty:difficulty.value})});selectedQ=x;sideMsg.textContent=`تم حفظ السؤال #${x.id}`;qs=await jfetch('/api/questions?limit=1000',{headers:h()});selectedQ=qs.find(z=>z.id==x.id);renderPageQs();await loadAsset();await renderStatus()}catch(e){sideMsg.textContent=e.message}}
async function pickQ(id){selectedQ=qs.find(x=>x.id==id);qtext.value=selectedQ.text_verbatim;subject.value=selectedQ.subject_id||'';grade.value=selectedQ.grade_level_id||'';curriculum.value=selectedQ.curriculum_version_id||'';renderAcademic();term.value=selectedQ.term_id||'';renderAcademic();unit.value=selectedQ.unit_id||'';renderAcademic();lesson.value=selectedQ.lesson_id||'';await loadConcepts();try{let cs=await jfetch('/api/questions/'+selectedQ.id+'/concepts',{headers:h()});let primary=cs.find(x=>x.is_primary)||cs[0];concept.value=primary?primary.id:''}catch(e){}try{let ss=await jfetch('/api/questions/'+selectedQ.id+'/skills',{headers:h()});let ps=ss.find(x=>x.is_primary)||ss[0];skill.value=ps?ps.id:''}catch(e){}qtype.value=selectedQ.question_type||'unknown';difficulty.value=selectedQ.difficulty||'unclassified';ans.value=selectedQ.accepted_answer||'';resetCrop();loadAsset();renderPageQs();renderStatus()}
function pt(e){let r=pageImg.getBoundingClientRect();return{x:Math.max(0,Math.min(r.width,e.clientX-r.left)),y:Math.max(0,Math.min(r.height,e.clientY-r.top)),w:r.width,h:r.height}}
stage.onpointerdown=e=>{if(!selectedQ){sideMsg.textContent='احفظ أو اختر السؤال قبل القص';return}drag=true;start=pt(e);stage.setPointerCapture(e.pointerId);selBox.style.display='block';draw(start,start)};stage.onpointermove=e=>{if(drag)draw(start,pt(e))};stage.onpointerup=e=>{if(!drag)return;drag=false;let p=pt(e),x=Math.min(start.x,p.x),y=Math.min(start.y,p.y),w=Math.abs(start.x-p.x),hh=Math.abs(start.y-p.y);draw(start,p);if(w<12||hh<12){resetCrop();return}crop={crop_x:x/p.w,crop_y:y/p.h,crop_width:w/p.w,crop_height:hh/p.h};sideMsg.textContent='تم التحديد؛ احفظ القصاصة'};
function draw(a,b){let x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.abs(a.x-b.x),hh=Math.abs(a.y-b.y);Object.assign(selBox.style,{left:x+'px',top:y+'px',width:w+'px',height:hh+'px'})}function resetCrop(){crop=null;selBox.style.display='none'}
async function saveCrop(){if(!selectedQ||!crop){sideMsg.textContent='حدد السؤال ثم اسحب حوله على الصفحة';return}try{await jfetch(`/api/questions/${selectedQ.id}/asset`,{method:'POST',headers:{...h(),'Content-Type':'application/json'},body:JSON.stringify(crop)});sideMsg.textContent='تم حفظ القصاصة';await loadAsset();renderStatus()}catch(e){sideMsg.textContent=e.message}}
async function loadAsset(){assetImg.removeAttribute('src');assetMeta.textContent='';if(!selectedQ)return;try{let a=await jfetch(`/api/questions/${selectedQ.id}/asset`,{headers:h()});let u=await blobUrl(`/api/questions/${selectedQ.id}/asset/image`);assetImg.src=u;assetImg.dataset.blob=u;assetMeta.textContent=`محفوظة · ${a.image_width}×${a.image_height} · صفحة ${a.page_number}`;selectedQ._asset=true}catch(e){selectedQ._asset=false;assetMeta.textContent='لا توجد قصاصة محفوظة بعد'}renderStatus()}
async function loadConcepts(){if(!lesson.value){concept.innerHTML='<option value="">اختر المفهوم الأساسي</option>';return}try{let xs=await jfetch('/api/academic/concepts?lesson_id='+lesson.value);concept.innerHTML='<option value="">اختر المفهوم الأساسي</option>'+xs.map(x=>`<option value="${x.id}">${x.title}</option>`).join('')}catch(e){concept.innerHTML='<option value="">تعذر تحميل المفاهيم</option>'}}
async function saveClassification(){if(!selectedQ){sideMsg.textContent='احفظ أو اختر السؤال أولًا';return}try{let x=await jfetch('/api/questions/'+selectedQ.id,{method:'PATCH',headers:{...h(),'Content-Type':'application/json'},body:JSON.stringify({lesson_id:lesson.value?Number(lesson.value):null,subject_id:subject.value?Number(subject.value):null,grade_level_id:grade.value?Number(grade.value):null,curriculum_version_id:curriculum.value?Number(curriculum.value):null,term_id:term.value?Number(term.value):null,unit_id:unit.value?Number(unit.value):null,question_type:qtype.value,difficulty:difficulty.value})});if(concept.value){await jfetch('/api/questions/'+selectedQ.id+'/concepts',{method:'PUT',headers:{...h(),'Content-Type':'application/json'},body:JSON.stringify({concept_ids:[Number(concept.value)],primary_concept_id:Number(concept.value)})})}if(skill.value){await jfetch('/api/questions/'+selectedQ.id+'/skills',{method:'PUT',headers:{...h(),'Content-Type':'application/json'},body:JSON.stringify({skill_ids:[Number(skill.value)],primary_skill_id:Number(skill.value)})})}sideMsg.textContent='تم حفظ التصنيف';qs=await jfetch('/api/questions?limit=1000',{headers:h()});selectedQ=qs.find(z=>z.id==x.id);selectedQ._asset=!!selectedQ.has_asset;renderPageQs();await renderStatus()}catch(e){sideMsg.textContent=e.message}}
async function renderStatus(){if(!selectedQ){status.innerHTML='<div class="check warn">ابدأ بحفظ سؤال من الصفحة أو اختر سؤالًا موجودًا.</div>';approveBtn.disabled=true;return}let r=null;try{r=await jfetch(`/api/questions/${selectedQ.id}/readiness`,{headers:h()})}catch(e){}let ready=r?r.ready_for_approval:!!selectedQ._asset;let state=r?r.workflow_state:(selectedQ.approved?'approved':(selectedQ._asset?'cropped':'draft'));let labels={draft:'مسودة',cropped:'تم القص',reviewed:'تمت المراجعة',approved:'معتمد'};let answerReady=!!((r&&r.accepted_answer&&String(r.accepted_answer).trim())||ans.value.trim());status.innerHTML=`<div class="check ${selectedQ.document_id?'ok':'warn'}">${selectedQ.document_id?'✅':'⚠️'} المصدر مرتبط</div><div class="check ${(selectedQ.source_page||selectedQ.page)?'ok':'warn'}">${(selectedQ.source_page||selectedQ.page)?'✅':'⚠️'} رقم الصفحة محفوظ</div><div class="check ${selectedQ._asset?'ok':'warn'}">${selectedQ._asset?'✅':'⚠️'} قصاصة المصدر ${selectedQ._asset?'محفوظة':'مطلوبة'}</div><div class="check ${r&&r.subject_id?'ok':'warn'}">${r&&r.subject_id?'✅':'⚠️'} المادة</div><div class="check ${r&&r.grade_level_id?'ok':'warn'}">${r&&r.grade_level_id?'✅':'⚠️'} الصف</div><div class="check ${r&&r.curriculum_version_id?'ok':'warn'}">${r&&r.curriculum_version_id?'✅':'⚠️'} إصدار المنهج</div><div class="check ${r&&r.term_id?'ok':'warn'}">${r&&r.term_id?'✅':'⚠️'} الترم</div><div class="check ${r&&r.unit_id?'ok':'warn'}">${r&&r.unit_id?'✅':'⚠️'} الوحدة</div><div class="check ${r&&r.lesson_id?'ok':'warn'}">${r&&r.lesson_id?'✅':'⚠️'} الدرس</div><div class="check ${r&&r.has_concept?'ok':'warn'}">${r&&r.has_concept?'✅':'⚠️'} المفهوم</div><div class="check ${r&&r.has_skill?'ok':'warn'}">${r&&r.has_skill?'✅':'⚠️'} المهارة</div><div class="check ${r&&r.question_type!='unknown'?'ok':'warn'}">${r&&r.question_type!='unknown'?'✅':'⚠️'} نوع السؤال</div><div class="check ${r&&r.difficulty!='unclassified'?'ok':'warn'}">${r&&r.difficulty!='unclassified'?'✅':'⚠️'} مستوى الصعوبة</div><div class="check ${answerReady?'ok':'warn'}">${answerReady?'✅':'⚠️'} الإجابة المعتمدة</div><div class="check ${state==='reviewed'||state==='approved'?'ok':'warn'}">الحالة: ${labels[state]||state}</div><div class="check ${ready&&answerReady?'ok':'warn'}">${ready&&answerReady?'✅ جاهز للاعتماد':'⚠️ أكمل البنود قبل الاعتماد'}</div>`;approveBtn.disabled=!(ready&&answerReady)
async function approve(){if(!selectedQ||!selectedQ._asset){sideMsg.textContent='لا يمكن الاعتماد قبل حفظ القصاصة';return}if(!concept.value){sideMsg.textContent='اختر المفهوم الأساسي قبل الاعتماد';return}if(!skill.value){sideMsg.textContent='اختر المهارة الأساسية قبل الاعتماد';return}if(!ans.value.trim()){sideMsg.textContent='أدخل الإجابة المعتمدة قبل الاعتماد';return}try{await jfetch('/api/questions/'+selectedQ.id+'/concepts',{method:'PUT',headers:{...h(),'Content-Type':'application/json'},body:JSON.stringify({concept_ids:[Number(concept.value)],primary_concept_id:Number(concept.value)})});await jfetch('/api/questions/'+selectedQ.id+'/skills',{method:'PUT',headers:{...h(),'Content-Type':'application/json'},body:JSON.stringify({skill_ids:[Number(skill.value)],primary_skill_id:Number(skill.value)})});let x=await jfetch('/api/questions/'+selectedQ.id,{method:'PATCH',headers:{...h(),'Content-Type':'application/json'},body:JSON.stringify({approved:true,accepted_answer:ans.value||null,lesson_id:lesson.value?Number(lesson.value):null,subject_id:subject.value?Number(subject.value):null,grade_level_id:grade.value?Number(grade.value):null,curriculum_version_id:curriculum.value?Number(curriculum.value):null,term_id:term.value?Number(term.value):null,unit_id:unit.value?Number(unit.value):null,question_type:qtype.value,difficulty:difficulty.value})});sideMsg.textContent='تم اعتماد السؤال';qs=await jfetch('/api/questions?limit=1000',{headers:h()});selectedQ=qs.find(z=>z.id==x.id);selectedQ._asset=true;renderPageQs();renderStatus()}catch(e){sideMsg.textContent=e.message}}
async function unapprove(){if(!selectedQ)return;try{await jfetch('/api/questions/'+selectedQ.id,{method:'PATCH',headers:{...h(),'Content-Type':'application/json'},body:JSON.stringify({approved:false})});qs=await jfetch('/api/questions?limit=1000',{headers:h()});selectedQ=qs.find(z=>z.id==selectedQ.id);sideMsg.textContent='تم إلغاء الاعتماد';renderPageQs();renderStatus()}catch(e){sideMsg.textContent=e.message}}
loadAll();
</script></html>'''

@app.get('/admin/workflow', response_class=HTMLResponse)
def admin_workflow():
    return WORKFLOW
