from __future__ import annotations

import json

from fastapi.responses import HTMLResponse

from . import lesson_pack_studio_ui
from .main import app


_PREVIEW_LINK_ANCHOR = '<div class=box><a href="/admin/lesson-pack-studio">Lesson Pack Studio</a> · <a href="/admin/dashboard">لوحة التحكم</a></div>'


def _enhance_pack_preview(html: str, job_id: str) -> str:
    if _PREVIEW_LINK_ANCHOR not in html:
        return html
    link = (
        _PREVIEW_LINK_ANCHOR[:-6]
        + f' · <a href="/admin/lesson-pack-studio/jobs/{job_id}/presentation">Presentation Studio</a></div>'
    )
    return html.replace(_PREVIEW_LINK_ANCHOR, link, 1)


_base_preview_page = lesson_pack_studio_ui._preview_page


def _preview_page_with_presentation_link(job_id: str) -> str:
    return _enhance_pack_preview(_base_preview_page(job_id), job_id)


lesson_pack_studio_ui._preview_page = _preview_page_with_presentation_link


def _workspace(job_id: str) -> str:
    safe_id = json.dumps(job_id)
    return r'''<!doctype html><html lang="ar" dir="rtl"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Lesson Presentation Studio</title><style>
*{box-sizing:border-box}body{font-family:system-ui;background:#f5f7fb;color:#172033;margin:0}main{max-width:1250px;margin:auto;padding:16px}.box{background:#fff;border-radius:16px;padding:16px;margin:10px 0;box-shadow:0 2px 12px #0001}.controls{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:10px}select,button,input,textarea{font:inherit;padding:10px;border:1px solid #ccd2dd;border-radius:10px;width:100%}textarea{min-height:84px;resize:vertical}button{cursor:pointer;background:#172033;color:#fff}button:disabled{opacity:.45;cursor:not-allowed}.muted{color:#667085;white-space:pre-wrap}.ok{color:#067647}.warn{color:#b54708}.bad{color:#b42318}.actions{display:flex;gap:10px;flex-wrap:wrap}.actions button{width:auto}.pill{display:inline-block;background:#f2f4f7;border-radius:999px;padding:3px 9px;font-size:12px}.features{display:flex;gap:6px;flex-wrap:wrap}.features span{background:#eef4ff;border-radius:999px;padding:4px 8px;font-size:12px}
.viewer{background:#101828;border-radius:18px;padding:12px;position:relative}.stage{aspect-ratio:16/9;background:#fff;border-radius:12px;overflow:auto;padding:5.5%;position:relative;box-shadow:0 14px 42px #0005}.stage h2{font-size:clamp(22px,3vw,42px);margin:0 0 20px}.stage p{font-size:clamp(15px,1.7vw,24px);line-height:1.65}.stage .ref{position:absolute;right:4%;left:4%;bottom:2%;font-size:11px;color:#667085;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.viewer-toolbar{display:flex;align-items:center;gap:8px;justify-content:center;margin-top:10px;flex-wrap:wrap}.viewer-toolbar button{width:auto;min-width:96px;background:#344054}.counter{color:#fff;min-width:100px;text-align:center}.filmstrip{display:flex;gap:8px;overflow:auto;padding:10px 0 2px}.thumb{min-width:150px;width:150px;aspect-ratio:16/9;border:2px solid transparent;border-radius:9px;background:#fff;color:#172033;padding:8px;text-align:right;overflow:hidden}.thumb.active{border-color:#84adff}.thumb.hidden-slide{opacity:.45}.thumb strong{font-size:12px;display:block}.thumb small{font-size:10px;color:#667085}.notes{margin-top:10px;border:1px dashed #98a2b3;border-radius:10px;padding:10px;background:#f9fafb}.hidden{display:none!important}.diagram{display:flex;align-items:center;gap:8px;justify-content:center;flex-wrap:wrap;margin:20px 0}.node{border:2px solid #98a2b3;border-radius:12px;padding:12px 16px;min-width:130px;text-align:center;font-weight:700;background:#f8fafc}.arrow{font-size:28px}.table-wrap{overflow:auto}.smart-table{border-collapse:collapse;width:100%;margin-top:16px}.smart-table th,.smart-table td{border:1px solid #d0d5dd;padding:8px;text-align:right}.smart-table th{background:#f2f4f7}.fullscreen-stage:fullscreen{background:#101828;padding:3vh}.fullscreen-stage:fullscreen .stage{height:88vh;aspect-ratio:auto}.fullscreen-stage:fullscreen .filmstrip{display:none}
.editor-grid{display:grid;grid-template-columns:minmax(240px,1fr) minmax(320px,2fr);gap:14px}.editor-panel{border:1px solid #e4e7ec;border-radius:12px;padding:12px}.editor-list{max-height:620px;overflow:auto}.field{margin:10px 0}.field label{display:block;font-weight:700;margin-bottom:5px}.editor-block{border:1px solid #e4e7ec;border-radius:10px;padding:10px;margin:8px 0}.editor-block small{color:#667085}.validation{border-radius:10px;padding:10px;background:#f9fafb}.dirty{border-color:#f79009!important;box-shadow:0 0 0 2px #f7900922}.approval-badge{font-weight:700}.slide-tools{display:flex;gap:8px;flex-wrap:wrap}.slide-tools button{width:auto}.secondary{background:#475467}.danger{background:#b42318}.success{background:#067647}@media(max-width:800px){.editor-grid{grid-template-columns:1fr}.editor-list{max-height:320px}}
</style><main>
<div class=box><a href="/admin/lesson-pack-studio/jobs/''' + job_id + r'''/preview">العودة إلى الملزمة</a> · <a href="/admin/dashboard">لوحة التحكم</a></div>
<div class=box><h1>Lesson Presentation Studio</h1><p>حوّل الملزمة الحالية إلى عرض تعليمي Source-Grounded، ثم عدّل الشرائح داخل المتصفح قبل التصدير مع فحص إلزامي وإعادة اعتماد بعد أي تعديل.</p><div id=policy class=muted>جارٍ تحميل مواصفات العرض...</div></div>
<div class=box><h2>إعداد العرض</h2><div class=controls>
<label>النمط<select id=mode></select></label><label>الجمهور<select id=audience><option value=student>طالب</option><option value=teacher>مدرس</option><option value=classroom>فصل دراسي</option></select></label><label>اللغة<select id=language><option value=ar>عربي</option><option value=en>English</option><option value=bilingual>عربي + English</option></select></label><label>الطول<select id=length><option value=short>قصير</option><option value=medium selected>متوسط</option><option value=full>كامل</option></select></label><label>القالب<select id=theme><option value=clean_academic>Clean Academic</option><option value=exam_night>Exam Night</option><option value=visual_concept>Visual Concept</option><option value=dark_classroom>Dark Classroom</option></select></label>
</div><p class=actions><button id=generate>إنشاء Blueprint</button><button id=studentPptx>تنزيل Student PPTX</button><button id=teacherPptx>تنزيل Teacher PPTX</button></p><p id=status class=muted>لم يتم إنشاء العرض بعد.</p></div>
<div class=box><h2>معاينة تفاعلية</h2><p class=muted>استخدم الأسهم من لوحة المفاتيح أو الشريط السفلي للتنقل. وضع المدرس يعرض Speaker Notes فقط عند الطلب.</p><div id=viewer class="viewer fullscreen-stage"><div id=stage class=stage><h2>أنشئ Blueprint لبدء المعاينة</h2></div><div class=viewer-toolbar><button id=prevSlide type=button>السابق</button><span id=slideCounter class=counter>— / —</span><button id=nextSlide type=button>التالي</button><button id=toggleNotes type=button>ملاحظات المدرس</button><button id=fullScreen type=button>ملء الشاشة</button></div><div id=filmstrip class=filmstrip></div></div></div>
<div class=box id=editorBox><h2>محرر الشرائح داخل المتصفح</h2><p class=muted>يمكن تعديل ترتيب الشرائح، إخفاؤها، العناوين، النصوص، Speaker Notes، ونصوص/تسميات المخططات. مراجع المصدر وهوية الشرائح وسياسة بنك الأسئلة غير قابلة للتغيير.</p><div class=editor-grid><div class="editor-panel editor-list"><div id=editorSlideList class=muted>أنشئ Blueprint أولًا.</div></div><div class=editor-panel><div id=editorEmpty class=muted>اختر شريحة من المعاينة أو القائمة.</div><div id=editorForm class=hidden><div class=field><label>عنوان الشريحة</label><input id=editTitle maxlength=240></div><div class=slide-tools><button id=moveUp type=button class=secondary>تحريك لأعلى</button><button id=moveDown type=button class=secondary>تحريك لأسفل</button><button id=toggleHidden type=button class=secondary>إخفاء الشريحة</button><button id=resetSlide type=button class=secondary>استرجاع الأصل</button></div><div class=field><label>النصوص</label><div id=editBlocks></div></div><div class=field><label>المخططات والرسومات</label><div id=editVisuals></div></div><div class=field><label>Speaker Notes</label><textarea id=editNotes placeholder="ملاحظة في كل سطر"></textarea></div><p class=actions><button id=applySlide type=button>تطبيق التعديل</button></p></div></div></div>
<div class=validation><div id=editState class=muted>لا توجد تعديلات.</div><p class=actions><button id=validateEdits type=button disabled>فحص التعديلات قبل التصدير</button><button id=approveEdits type=button class=success disabled>إعادة اعتماد المدرس</button><button id=resetDeck type=button class=secondary disabled>إلغاء كل التعديلات</button></p><div id=validationResult class=muted></div></div></div>
<div class=box><h2>القدرات المفعلة</h2><div id=features class=features></div></div>
<script>
const id=''' + safe_id + r''';let blueprint=null,baseBlueprint=null,currentSlide=0,notesVisible=false,editorBaseHash='',dirty=false,validationDigest='',teacherReapproved=false;const $=x=>document.getElementById(x);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const clone=x=>JSON.parse(JSON.stringify(x));
const mode=$('mode'),audience=$('audience'),language=$('language'),length=$('length'),theme=$('theme'),status=$('status'),features=$('features'),policy=$('policy'),stage=$('stage'),filmstrip=$('filmstrip'),slideCounter=$('slideCounter');const studentPptx=$('studentPptx'),teacherPptx=$('teacherPptx'),validateEdits=$('validateEdits'),approveEdits=$('approveEdits'),resetDeck=$('resetDeck'),editState=$('editState'),validationResult=$('validationResult');
function payload(audienceOverride=null){return {mode:mode.value,audience:audienceOverride||audience.value,language:language.value,length:length.value,theme:theme.value,include:{examples:true,laws:true,visuals:true,tables:true,activities:true,checkpoints:true,speaker_notes:(audienceOverride||audience.value)!=='student'}}}
async function boot(){let r=await fetch('/api/admin/lesson-pack-studio/presentation/feature-specs');if(r.status===401){location.href='/admin/login';return}let x=await r.json();mode.innerHTML=x.modes.map(v=>'<option value="'+esc(v)+'">'+esc(v)+'</option>').join('');features.innerHTML=x.features.map(f=>'<span>'+f.card+'. '+esc(f.title)+(f.enabled?'':' · مؤجل')+'</span>').join('');policy.textContent='20 بطاقة → '+x.features.length+' مواصفة · Slide Editor: '+(x.slide_editor&&x.slide_editor.enabled?'مفعّل':'غير مفعّل')+' · بنك الأسئلة الرسمي: معزول · Content Ingestion: بدون تغيير';}
function visualLabels(v){let out=[];['nodes','steps','items','labels'].forEach(k=>{if(Array.isArray(v[k]))v[k].forEach(n=>{let t=typeof n==='object'?(n.label||n.title||n.text):n;if(t)out.push(String(t))})});if(!out.length&&v.description)out=String(v.description).replaceAll('→','|').replaceAll('->','|').split('|').map(x=>x.trim()).filter(Boolean);if(!out.length)out=[v.title||v.kind||'رسم توضيحي'];return out.slice(0,6)}
function renderDiagram(v){let engine=v&&v.diagram_engine;if(engine&&engine.svg&&engine.valid!==false){return '<div class=diagram style="display:block;overflow:auto">'+engine.svg+'</div><div class=muted>'+esc(v.kind||'diagram')+' · source-grounded · editable PPTX native render</div>'}let labels=visualLabels(v);return '<div class=diagram>'+labels.map((t,i)=>'<div class=node>'+esc(t)+'</div>'+(i<labels.length-1?'<span class=arrow>←</span>':'')).join('')+'</div><div class=muted>'+esc(v.kind||'diagram')+(v.generated?' · generated_visual':' · source_visual')+'</div>'}
function renderTable(t){let cols=t.columns||[],rows=t.rows||[];if(!cols.length||!rows.length)return '';return '<div class=table-wrap><table class=smart-table><thead><tr>'+cols.map(c=>'<th>'+esc(c)+'</th>').join('')+'</tr></thead><tbody>'+rows.slice(0,7).map(r=>'<tr>'+cols.map(c=>'<td>'+esc(r[c]||'')+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'}
function renderCurrent(){if(!blueprint||!blueprint.slides||!blueprint.slides.length){stage.innerHTML='<h2>لا توجد شرائح</h2>';return}currentSlide=Math.max(0,Math.min(currentSlide,blueprint.slides.length-1));let s=blueprint.slides[currentSlide];let blocks=(s.content_blocks||[]).filter(b=>audience.value!=='student'||!b.teacher_only);let body=blocks.map(b=>'<p>'+esc(b.text)+'</p>').join('');let visuals=(s.visual_specs||[]).map(renderDiagram).join('');let tables=(s.table_specs||[]).map(renderTable).join('');let notes=(s.speaker_notes||[]).map(n=>'<div>• '+esc(n)+'</div>').join('');stage.classList.toggle('dirty',!!s.hidden);stage.innerHTML='<span class=pill>'+esc(s.kind)+(s.hidden?' · مخفية':'')+'</span><h2>'+esc(s.title)+'</h2>'+body+visuals+tables+(notesVisible&&audience.value!=='student'&&notes?'<div class=notes><b>Speaker Notes</b>'+notes+'</div>':'')+'<div class=ref>'+esc((s.source_refs||[]).join(' · '))+'</div>';slideCounter.textContent=(currentSlide+1)+' / '+blueprint.slides.length;filmstrip.querySelectorAll('.thumb').forEach((el,i)=>el.classList.toggle('active',i===currentSlide));let active=filmstrip.children[currentSlide];if(active)active.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});loadEditor();}
function buildFilmstrip(){filmstrip.innerHTML=(blueprint.slides||[]).map((s,i)=>'<button type=button class="thumb '+(i===currentSlide?'active ':'')+(s.hidden?'hidden-slide':'')+'" data-i="'+i+'"><strong>'+(i+1)+'. '+esc(s.title)+'</strong><small>'+esc(s.kind)+(s.hidden?' · مخفية':'')+'</small></button>').join('');filmstrip.querySelectorAll('.thumb').forEach(b=>b.onclick=()=>{currentSlide=Number(b.dataset.i);renderCurrent()});buildEditorList()}
function buildEditorList(){let root=$('editorSlideList');if(!blueprint){root.innerHTML='أنشئ Blueprint أولًا.';return}root.innerHTML=blueprint.slides.map((s,i)=>'<button type=button class="thumb '+(s.hidden?'hidden-slide':'')+'" style="width:100%;min-width:0;margin-bottom:7px" data-ei="'+i+'"><strong>'+(i+1)+'. '+esc(s.title)+'</strong><small>'+esc(s.kind)+(s.hidden?' · مخفية':'')+'</small></button>').join('');root.querySelectorAll('[data-ei]').forEach(b=>b.onclick=()=>{currentSlide=Number(b.dataset.ei);renderCurrent()})}
function render(x){editorBaseHash=x.editor_base_hash||'';delete x.editor_base_hash;blueprint=x;baseBlueprint=clone(x);currentSlide=0;notesVisible=false;dirty=false;validationDigest='';teacherReapproved=false;let pre=x.preflight||{};status.className=pre.ready?'ok':'warn';status.textContent=(pre.ready?'✅ Blueprint جاهز':'⛔ يحتاج استكمال')+' · عدد الشرائح: '+(pre.slide_count||0)+(pre.blocking_failures&&pre.blocking_failures.length?' · '+pre.blocking_failures.join('، '):'');buildFilmstrip();renderCurrent();updateEditState()}
function markDirty(){dirty=true;validationDigest='';teacherReapproved=false;validationResult.textContent='تم تغيير العرض. يلزم فحص التعديلات ثم إعادة اعتماد المدرس قبل التصدير.';updateEditState()}
function updateEditState(){validateEdits.disabled=!blueprint||!dirty;approveEdits.disabled=true;resetDeck.disabled=!blueprint||!dirty;studentPptx.disabled=!!dirty&&!teacherReapproved;teacherPptx.disabled=!!dirty&&!teacherReapproved;if(!blueprint){editState.textContent='لا يوجد Blueprint.';return}if(!dirty){editState.className='ok';editState.textContent='✅ لا توجد تعديلات غير معتمدة. التصدير متاح.'}else if(teacherReapproved){editState.className='ok';editState.textContent='✅ التعديلات مفحوصة ومعتمدة. التصدير متاح.'}else if(validationDigest){editState.className='warn';editState.textContent='⚠️ الفحص ناجح، لكن اعتماد المدرس أُلغي بسبب التعديل. اضغط إعادة اعتماد المدرس.'}else{editState.className='warn';editState.textContent='⚠️ توجد تعديلات. التصدير متوقف حتى الفحص وإعادة الاعتماد.'}}
function loadEditor(){let empty=$('editorEmpty'),form=$('editorForm');if(!blueprint||!blueprint.slides[currentSlide]){empty.classList.remove('hidden');form.classList.add('hidden');return}empty.classList.add('hidden');form.classList.remove('hidden');let s=blueprint.slides[currentSlide];$('editTitle').value=s.title||'';$('toggleHidden').textContent=s.hidden?'إظهار الشريحة':'إخفاء الشريحة';$('moveUp').disabled=currentSlide===0;$('moveDown').disabled=currentSlide===blueprint.slides.length-1;$('editNotes').value=(s.speaker_notes||[]).join('\n');$('editBlocks').innerHTML=(s.content_blocks||[]).map((b,i)=>'<div class=editor-block><small>'+esc(b.kind)+(b.teacher_only?' · teacher_only':'')+'</small><textarea data-block="'+i+'">'+esc(b.text||'')+'</textarea></div>').join('')||'<div class=muted>لا توجد كتل نصية.</div>';$('editVisuals').innerHTML=(s.visual_specs||[]).map((v,i)=>'<div class=editor-block data-visual="'+i+'"><small>'+esc(v.kind)+(v.generated?' · generated_visual':' · source_visual')+'</small><div class=field><label>العنوان</label><input data-vtitle value="'+esc(v.title||'')+'"></div><div class=field><label>الوصف</label><textarea data-vdesc>'+esc(v.description||'')+'</textarea></div><div class=field><label>التسميات — سطر لكل عنصر</label><textarea data-vlabels>'+esc((v.labels||[]).map(x=>typeof x==='object'?(x.label||x.title||x.text||''):x).join('\n'))+'</textarea></div></div>').join('')||'<div class=muted>لا توجد مخططات في هذه الشريحة.</div>'}
$('applySlide').onclick=()=>{if(!blueprint)return;let s=blueprint.slides[currentSlide];s.title=$('editTitle').value.trim();$('editBlocks').querySelectorAll('[data-block]').forEach(el=>{let i=Number(el.dataset.block);if(s.content_blocks&&s.content_blocks[i])s.content_blocks[i].text=el.value.trim()});$('editVisuals').querySelectorAll('[data-visual]').forEach(box=>{let i=Number(box.dataset.visual),v=s.visual_specs&&s.visual_specs[i];if(!v)return;v.title=box.querySelector('[data-vtitle]').value.trim();v.description=box.querySelector('[data-vdesc]').value.trim();let labels=box.querySelector('[data-vlabels]').value.split('\n').map(x=>x.trim()).filter(Boolean);if(labels.length)v.labels=labels;else delete v.labels});s.speaker_notes=$('editNotes').value.split('\n').map(x=>x.trim()).filter(Boolean);markDirty();buildFilmstrip();renderCurrent()};
$('moveUp').onclick=()=>{if(!blueprint||currentSlide<=0)return;let a=blueprint.slides;[a[currentSlide-1],a[currentSlide]]=[a[currentSlide],a[currentSlide-1]];currentSlide--;a.forEach((s,i)=>s.order=i+1);markDirty();buildFilmstrip();renderCurrent()};$('moveDown').onclick=()=>{if(!blueprint||currentSlide>=blueprint.slides.length-1)return;let a=blueprint.slides;[a[currentSlide+1],a[currentSlide]]=[a[currentSlide],a[currentSlide+1]];currentSlide++;a.forEach((s,i)=>s.order=i+1);markDirty();buildFilmstrip();renderCurrent()};$('toggleHidden').onclick=()=>{if(!blueprint)return;let s=blueprint.slides[currentSlide];s.hidden=!s.hidden;markDirty();buildFilmstrip();renderCurrent()};
$('resetSlide').onclick=()=>{if(!blueprint||!baseBlueprint)return;let sid=blueprint.slides[currentSlide].slide_id,orig=baseBlueprint.slides.find(s=>s.slide_id===sid);if(!orig)return;blueprint.slides[currentSlide]=clone(orig);blueprint.slides[currentSlide].order=currentSlide+1;markDirty();buildFilmstrip();renderCurrent()};$('resetDeck').onclick=()=>{if(!baseBlueprint)return;blueprint=clone(baseBlueprint);dirty=false;validationDigest='';teacherReapproved=false;currentSlide=0;validationResult.textContent='تم إلغاء كل التعديلات.';buildFilmstrip();renderCurrent();updateEditState()};
validateEdits.onclick=async()=>{if(!blueprint||!dirty)return;validationResult.className='muted';validationResult.textContent='جارٍ فحص التعديلات ومراجع المصدر وسياسة العرض...';let p=payload();p.edited_blueprint=blueprint;p.editor_base_hash=editorBaseHash;let r=await fetch('/api/admin/lesson-pack-studio/jobs/'+id+'/presentation/editor/preflight',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});let x=await r.json();if(!r.ok||!x.ready){validationDigest='';teacherReapproved=false;validationResult.className='bad';validationResult.textContent='⛔ فشل الفحص: '+JSON.stringify(x.detail||x);updateEditState();return}validationDigest=x.edit_digest||'';teacherReapproved=false;approveEdits.disabled=!validationDigest;validationResult.className='ok';validationResult.textContent='✅ الفحص ناجح · الشرائح الظاهرة: '+x.visible_slide_count+' · المخفية: '+x.hidden_slide_count+' · اعتماد المدرس مطلوب بعد التعديل.';updateEditState();approveEdits.disabled=!validationDigest};
approveEdits.onclick=()=>{if(!validationDigest)return;teacherReapproved=true;validationResult.className='ok';validationResult.textContent='✅ تم إعادة اعتماد المدرس لهذه النسخة المفحوصة. أي تعديل جديد سيلغي الاعتماد تلقائيًا.';updateEditState()};
$('generate').onclick=async()=>{status.textContent='جارٍ إنشاء Blueprint...';let r=await fetch('/api/admin/lesson-pack-studio/jobs/'+id+'/presentation/blueprint',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});let x=await r.json();if(!r.ok){status.className='bad';status.textContent=JSON.stringify(x.detail||x);return}render(x)};
$('prevSlide').onclick=()=>{if(blueprint){currentSlide--;renderCurrent()}};$('nextSlide').onclick=()=>{if(blueprint){currentSlide++;renderCurrent()}};$('toggleNotes').onclick=()=>{notesVisible=!notesVisible;renderCurrent()};$('fullScreen').onclick=()=>{let v=$('viewer');if(document.fullscreenElement)document.exitFullscreen();else if(v.requestFullscreen)v.requestFullscreen()};audience.onchange=()=>renderCurrent();
document.addEventListener('keydown',e=>{if(!blueprint||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;if(e.key==='ArrowLeft'){currentSlide++;renderCurrent()}else if(e.key==='ArrowRight'){currentSlide--;renderCurrent()}else if(e.key==='Home'){currentSlide=0;renderCurrent()}else if(e.key==='End'){currentSlide=blueprint.slides.length-1;renderCurrent()}});
async function download(edition){status.textContent='جارٍ تجهيز '+edition+' PPTX...';let p=payload(edition);if(dirty){p.edited_blueprint=blueprint;p.editor_base_hash=editorBaseHash;p.validation_digest=validationDigest;p.teacher_reapproved=teacherReapproved}let r=await fetch('/api/admin/lesson-pack-studio/jobs/'+id+'/presentation/export-pptx/'+edition,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});if(!r.ok){let x=await r.json();status.className='bad';status.textContent=JSON.stringify(x.detail||x);return}let blob=await r.blob();let url=URL.createObjectURL(blob);let a=document.createElement('a');a.href=url;a.download='lesson-presentation-'+edition+'-'+id+'.pptx';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);status.className='ok';status.textContent='✅ تم تجهيز '+edition+' PPTX بنجاح.'}
studentPptx.onclick=()=>download('student');teacherPptx.onclick=()=>download('teacher');boot();
</script></main></html>'''


@app.get("/admin/lesson-pack-studio/jobs/{job_id}/presentation", response_class=HTMLResponse)
def lesson_presentation_workspace(job_id: str):
    return _workspace(job_id)
