from __future__ import annotations

import logging

from . import lesson_studio_workspace as workspace


log = logging.getLogger(__name__)

_PATCH = r'''

function diagramSpecErrorText(x){let es=(x?.validation?.errors||x?.detail?.validation?.errors||[]);return es.map(e=>`${e.path}: ${e.message}`).join('\n')||JSON.stringify(x?.detail||x||'تعذر التحقق')}
function diagramSpecParams(i){try{return JSON.parse($(`#diagram-params-${i}`).value)}catch(e){throw new Error('JSON غير صالح: '+e.message)}}
function renderDiagrams(){let supported=['resistor_network','series_parallel_circuit','ray_diagram','magnetic_field','solenoid_field','molecule_bond','chemistry_lab_setup','force_diagram','graph_plot','particle_model','reaction_profile','cell_structure','food_web','earth_layers'];let rows=(state.content.diagram_specs||[]).map((d,i)=>{let e=d.diagram_engine||{},params=JSON.stringify(d.parameters||{},null,2),kind=d.normalized_kind||d.kind,canEdit=supported.includes(kind),validated=e.schema_validated===true,versioned=d.diagram_spec_versioned===true;return `<div class=card><h3>${esc(d.title)}</h3><p>${esc(d.description||'')}</p><div class=muted>${esc((d.scientific_labels||[]).join('، '))}</div>${e.svg?`<div class=svg>${e.svg}</div>`:'<div class=warn>لا يوجد Renderer دقيق أو المواصفات الصريحة غير مكتملة.</div>'}<p>${badge(e.review_required?'yellow':'green')} ${e.review_required?'يحتاج اعتماد المدرس':'جاهز'} ${e.parameterized?'<span class="pill approved">Parameterized</span>':''} ${validated?'<span class="pill green">Schema Validated</span>':'<span class="pill yellow">Schema Pending</span>'} ${versioned?'<span class="pill approved">Versioned</span>':''}</p>${canEdit?`<details open><summary><b>Diagram Spec Editor · ${esc(kind)}</b></summary><p class=muted>Preview لا يحفظ ولا يغيّر الاعتماد. Save يمر أولًا بالـstrict schema، ثم يسجل نسخة immutable ويلغي الاعتمادات القديمة التي تعتمد على الرسم السابق.</p><textarea id="diagram-params-${i}" dir=ltr>${esc(params)}</textarea><div class=row><button onclick="previewDiagramSpec(${i})">Validate + Preview</button><button class=primary onclick="saveDiagramSpec(${i})">حفظ Spec جديدة</button><button onclick="loadDiagramHistory(${i})">سجل نسخ الرسم</button><a href="/admin/lesson-studio/diagram-specs" target=_blank>فتح Specification Builder</a></div><div id="diagram-spec-status-${i}" class=muted></div><div id="diagram-preview-${i}" class=svg></div><div id="diagram-history-${i}"></div></details>`:''}${e.review_required&&e.svg?`<button class=primary onclick="approveDiagram(${i})">اعتماد الرسم بعد المراجعة</button>`:''}</div>`}).join('');$('#diagrams').innerHTML=rows||'<div class=card>لا توجد رسومات مقترحة.</div>'}
async function previewDiagramSpec(i){let status=$(`#diagram-spec-status-${i}`),preview=$(`#diagram-preview-${i}`);try{status.textContent='جارٍ التحقق...';preview.innerHTML='';let x=await api(`/api/admin/lesson-studio/jobs/${encodeURIComponent(jobId())}/diagrams/${i}/spec/preview`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({parameters:diagramSpecParams(i)})});if(!x.valid){status.className='warn';status.innerHTML='<b>مرفوض قبل الـrenderer</b><pre>'+esc(diagramSpecErrorText(x))+'</pre>';return}status.className='ok';status.textContent='المواصفات صالحة. المعاينة لم تغيّر حالة الاعتماد.';preview.innerHTML=x.svg||''}catch(e){status.className='warn';status.textContent=e.message}}
async function saveDiagramSpec(i){let status=$(`#diagram-spec-status-${i}`);try{let parameters=diagramSpecParams(i);let note=window.prompt('ملاحظة اختيارية لهذا الإصدار:','تعديل مواصفات الرسم من Workspace')||'';let x=await api(`/api/admin/lesson-studio/jobs/${encodeURIComponent(jobId())}/diagrams/${i}/spec`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({parameters,note})});status.className='ok';status.textContent=`تم الحفظ كنسخة رسم v${x.spec_version?.version_no||''}. تم إلغاء الاعتمادات المرتبطة بالنسخة السابقة.`;await load()}catch(e){status.className='warn';status.textContent=e.message}}
async function updateDiagramParameters(i){return saveDiagramSpec(i)}
async function loadDiagramHistory(i){let box=$(`#diagram-history-${i}`);try{box.innerHTML='<p class=muted>جارٍ تحميل سجل الرسم...</p>';let x=await api(`/api/admin/lesson-studio/jobs/${encodeURIComponent(jobId())}/diagrams/${i}/spec-history`);let rows=(x.versions||[]).map(v=>`<div class=section><b>Diagram v${v.version_no}</b> · ${esc(v.action)} · <span class=muted>${esc(v.created_at||'')}</span><br><span class=muted>hash: ${esc(String(v.diagram_hash||'').slice(0,12))}</span>${v.note?`<div>${esc(v.note)}</div>`:''}<details><summary>Parameters</summary><pre dir=ltr>${esc(JSON.stringify(v.parameters||{},null,2))}</pre></details><button onclick="restoreDiagramSpec(${i},${v.version_no})">استرجاع هذه النسخة للرسم فقط</button></div>`).join('');box.innerHTML=`<div class=card><h4>سجل مواصفات الرسم</h4><p class=muted>Current hash: ${esc(String(x.current?.diagram_hash||'').slice(0,12))} · الاسترجاع يعيد هذا الرسم فقط، ولا يمس المصدر أو بقية الدرس.</p>${rows||'<p class=muted>لا توجد نسخ.</p>'}</div>`}catch(e){box.innerHTML='<div class=warn>'+esc(e.message)+'</div>'}}
async function restoreDiagramSpec(i,v){if(!window.confirm('استرجاع Diagram v'+v+'؟ سيتم إعادة التحقق بالـSchema الحالي وإلغاء اعتماد الدرس والمراجعات المرتبطة بالرسم الحالي.'))return;let fd=new FormData();fd.append('teacher_note','استرجاع مواصفات الرسم من Workspace');try{let x=await api(`/api/admin/lesson-studio/jobs/${encodeURIComponent(jobId())}/diagrams/${i}/spec-history/${v}/restore`,{method:'POST',body:fd});alert('تم استرجاع Diagram v'+v+' وتسجيل الاسترجاع كنسخة جديدة.');await load()}catch(e){alert(e.message)}}
'''

_MARKER = '</script></main></html>'
if _MARKER not in workspace.WORKSPACE:
    log.warning('Lesson Studio Workspace closing marker not found; diagram editor patch skipped')
elif 'function previewDiagramSpec(i)' not in workspace.WORKSPACE:
    workspace.WORKSPACE = workspace.WORKSPACE.replace(_MARKER, _PATCH + '\n' + _MARKER)
