from __future__ import annotations

import json

from fastapi.responses import HTMLResponse

from .main import app


HOME_PAGE = r"""<!doctype html><html lang="ar" dir="rtl"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Lesson Pack Studio</title><style>
*{box-sizing:border-box}body{font-family:system-ui;background:#f5f7fb;color:#172033;margin:0}main{max-width:1000px;margin:auto;padding:18px}
.box{background:#fff;border-radius:16px;padding:16px;margin:12px 0;box-shadow:0 2px 12px #0001}.row{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}
input,select,button{font:inherit;padding:10px;border:1px solid #ccd2dd;border-radius:10px;width:100%}button{cursor:pointer;background:#172033;color:#fff}
.muted{color:#667085;white-space:pre-wrap}.ok{color:#067647}.warn{color:#b54708}</style><main>
<div class=box><a href="/admin/dashboard">لوحة التحكم</a> · <a href="/admin/lesson-studio">Lesson Studio</a></div>
<div class=box><h1>Lesson Pack Studio</h1><p>حوّل PDF أو Scan إلى ملزمة طالب احترافية جاهزة للطباعة والمذاكرة: شرح متدرج، قوانين ومفاهيم، أمثلة، رسومات، تدريبات ومساحة للحل، مع نسخة مدرس منفصلة بالإجابات.</p><div id=status class=muted>جارٍ تحميل الحالة...</div></div>
<form id=f class=box><div class=row><input name=title placeholder="عنوان الدرس" required><select name=subject><option value=physics>فيزياء</option><option value=chemistry>كيمياء</option><option value=science>علوم</option></select><input name=grade_label placeholder="الصف"><select name=pack_mode><option value=balanced>متوازن</option><option value=exam_revision>مراجعة امتحان</option><option value=concept_mastery>إتقان المفاهيم</option></select></div><p><input name=files type=file accept=".pdf,image/*" multiple required></p><button>إنشاء ملزمة الطالب</button></form>
<div class=box><div id=out class=muted>لم تبدأ عملية بعد.</div></div>
<script>
async function boot(){let r=await fetch('/api/admin/lesson-pack-studio/status');if(r.status===401){location.href='/admin/login';return}let x=await r.json();status.textContent='الرفع: '+(x.ingestion_enabled?'مفعل':'متوقف')+' · OCR: '+x.ocr_provider+' · التخزين: '+(x.storage_configured?'جاهز':'غير مهيأ')+' · بنك الأسئلة الرسمي: معزول';}
async function processAll(id,total){let done=false;while(!done){let r=await fetch('/api/admin/lesson-pack-studio/jobs/'+id+'/process-next',{method:'POST'});let x=await r.json();if(!r.ok)throw new Error(JSON.stringify(x.detail||x));done=!!x.done;out.textContent='OCR: '+x.processed+' / '+total+' · صفحات تحتاج مراجعة: '+x.review_pages;}let fd=new FormData();fd.append('question_count','12');let g=await fetch('/api/admin/lesson-pack-studio/jobs/'+id+'/generate',{method:'POST',body:fd});let y=await g.json();if(!g.ok)throw new Error(JSON.stringify(y.detail||y));location.href='/admin/lesson-pack-studio/jobs/'+id+'/preview';}
f.addEventListener('submit',async e=>{e.preventDefault();out.textContent='جارٍ تجهيز الصفحات...';try{let r=await fetch('/api/admin/lesson-pack-studio/jobs',{method:'POST',body:new FormData(f)});let x=await r.json();if(!r.ok)throw new Error(JSON.stringify(x.detail||x));out.textContent='تم إنشاء المشروع. بدء OCR صفحة بصفحة...';await processAll(x.id,x.source_page_count)}catch(err){out.textContent='خطأ: '+err.message}});boot();
</script></main></html>"""


@app.get("/admin/lesson-pack-studio", response_class=HTMLResponse)
def lesson_pack_home():
    return HOME_PAGE


def _preview_page(job_id: str) -> str:
    safe_id = json.dumps(job_id)
    return r"""<!doctype html><html lang="ar" dir="rtl"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>مراجعة Lesson Pack</title><style>
*{box-sizing:border-box}body{font-family:system-ui;background:#f5f7fb;color:#172033;margin:0}main{max-width:1200px;margin:auto;padding:16px}
.box{background:#fff;border-radius:16px;padding:16px;margin:10px 0;box-shadow:0 2px 12px #0001}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:12px}
.page{border:1px solid #e4e7ec;border-radius:12px;padding:10px}.page img{width:100%;max-height:360px;object-fit:contain;background:#fafafa}
textarea{width:100%;min-height:180px;font:inherit;padding:10px}button,input{font:inherit;padding:9px;border:1px solid #ccd2dd;border-radius:9px}button{cursor:pointer}.primary{background:#172033;color:#fff}
.ok{color:#067647}.warn{color:#b54708}.bad{color:#b42318}.muted{color:#667085;white-space:pre-wrap}.q{border:1px solid #e4e7ec;border-radius:10px;padding:10px;margin:8px 0}details{margin-top:8px}.visual-card{border:1px solid #e4e7ec;border-radius:12px;padding:10px}.visual-card img{width:100%;max-height:300px;object-fit:contain;background:#fafafa}.crop-grid{display:grid;grid-template-columns:repeat(4,minmax(70px,1fr));gap:6px}.crop-grid input{width:100%}.action-row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.action-row button{width:auto}.cover-fields{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px}.cover-fields label{font-size:12px;color:#475467}.cover-fields input{display:block;width:100%;margin-top:4px}.preview-shell{display:grid;grid-template-columns:minmax(0,1fr);gap:10px}.preview-toolbar{display:flex;gap:8px;align-items:center;justify-content:center;flex-wrap:wrap}.preview-toolbar button{width:auto;min-width:95px}.preview-page{display:block;width:min(100%,820px);max-height:82vh;object-fit:contain;margin:auto;border:1px solid #d0d5dd;border-radius:12px;background:#fff;box-shadow:0 8px 30px #10182818}.preview-meta{text-align:center;color:#475467;font-weight:700}
</style><main><div class=box><a href="/admin/lesson-pack-studio">Lesson Pack Studio</a> · <a href="/admin/dashboard">لوحة التحكم</a></div>
<div id=head class=box>جارٍ التحميل...</div><div id=pack class=box></div>
<form id=coverForm class=box><h2>غلاف الملزمة وبيانات الطالب</h2><p class=muted>البيانات اختيارية؛ إذا تركت أي خانة فارغة تظهر مساحة كتابة على الغلاف المطبوع. حفظ أي تعديل يلغي الاعتماد النهائي السابق حتى تراجع النسخة الجديدة.</p><div class=cover-fields><label>اسم الطالب<input id=coverStudent name=student_name maxlength=120 placeholder="يُترك فارغًا لملزمة عامة"></label><label>الصف / الفصل<input id=coverClass name=class_label maxlength=120></label><label>اسم المدرس<input id=coverTeacher name=teacher_name maxlength=120></label><label>المدرسة / السنتر<input id=coverSchool name=school_name maxlength=120></label><label>العام / الترم<input id=coverTerm name=academic_term maxlength=120 placeholder="مثال: الترم الأول 2026/2027"></label></div><p><button class=primary>حفظ الغلاف وتحديث المعاينة</button></p></form>
<div class=box><h2>مراجعة صفحات المصدر</h2><div id=pages class=grid></div></div>
<div class=box><h2>الصور والرسومات الأصلية من المصدر</h2><p class=muted>يتم اكتشاف الأشكال المرتبطة بالشرح من الصفحة الأصلية فقط. لا يتم توليد صورة بديلة، ولا تدخل أي قصاصة في ملزمة الطالب إلا بعد اعتمادك لها.</p><p><button id=suggestVisuals>اكتشاف صور المصدر المرتبطة بالدرس</button></p><div id=visuals class=grid></div></div>
<div class=box><h2>معاينة A4 صفحة بصفحة</h2><p class=muted>المعاينة تحمل علامة «غير معتمدة». تنقّل بين الصفحات واحدة واحدة، أو افتح PDF الكامل، قبل الاعتماد النهائي.</p><div class=action-row><button id=studentPreview type=button>نسخة الطالب</button><button id=teacherPreview type=button>نسخة المدرس</button><a id=openFullPreview target=_blank rel=noopener>فتح PDF الكامل</a></div><div class=preview-shell><div class=preview-toolbar><button id=prevPage type=button>السابق</button><span id=pageCounter class=preview-meta>صفحة —</span><button id=nextPage type=button>التالي</button></div><img id=pagePreview class=preview-page alt="معاينة صفحة الملزمة"></div></div>
<div class=box><h2>إجراءات الجودة</h2><div class=grid><button id=regen>إعادة توليد الملزمة</button><button id=sci>المراجعة العلمية المستقلة</button><button id=approve class=primary>اعتماد نهائي</button></div><p><label><input id=confirmSource type=checkbox> راجعت المصدر وأؤكد أن الملزمة مرتبطة به</label></p><p><label><input id=acceptFindings type=checkbox> قرأت ملاحظات المراجع العلمي وأقبلها عند وجود findings تحتاج مراجعة</label></p><p id=action class=muted></p><p><a id=studentPdf href="#">ملزمة الطالب PDF</a> · <a id=teacherPdf href="#">نسخة المدرس PDF</a></p></div>
<script>
const id=""" + safe_id + r"""; const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data,previewEdition='student',previewPage=1,previewTotal=0,previewManifestCache={};
function invalidatePreview(){previewManifestCache={};}
async function load(){let r=await fetch('/api/admin/lesson-pack-studio/jobs/'+id);if(r.status===401){location.href='/admin/login';return}data=await r.json();if(!r.ok){head.textContent=JSON.stringify(data);return}
head.innerHTML='<h1>'+esc(data.title)+'</h1><p class=muted>'+esc(data.subject)+' · '+esc(data.grade_label)+' · الحالة: '+esc(data.status)+'</p><p>OCR: '+data.progress.transcribed_pages+'/'+data.progress.total_pages+' · مراجعة مطلوبة: '+data.progress.review_pages+' · اعتماد المدرس: '+(data.teacher_approved?'✅':'⏳')+'</p>';
let p=data.pack_json||{};let qs=p.practice_questions||[];pack.innerHTML='<h2>معاينة الملزمة</h2><p>'+esc(p.summary||'لم يتم التوليد بعد')+'</p>'+((p.sections||[]).map(s=>'<div><h3>'+esc(s.heading)+'</h3><p>'+esc(s.body)+'</p><small>'+esc((s.source_refs||[]).join('، '))+'</small></div>').join(''))+'<h3>التدريبات ('+qs.length+')</h3>'+qs.map((q,i)=>'<div class=q><b>'+(i+1)+') '+esc(q.prompt)+'</b><div class=muted>'+esc((q.source_refs||[]).join('، '))+'</div><details><summary>الإجابة والتفسير</summary><p>'+esc(q.answer)+'</p><p>'+esc(q.explanation)+'</p></details></div>').join('');
let hasCover=!!p.cover&&typeof p.cover==='object';let cv=hasCover?p.cover:{};coverStudent.value=cv.student_name||'';coverClass.value=hasCover?(cv.class_label||''):(data.grade_label||'');coverTeacher.value=cv.teacher_name||'';coverSchool.value=cv.school_name||'';coverTerm.value=cv.academic_term||'';
pages.innerHTML=data.pages.map(pg=>'<div class=page><h3>'+esc(pg.source_ref)+'</h3><img src="'+esc(pg.image_url)+'"><textarea id="t'+pg.id+'">'+esc(pg.extracted_text||'')+'</textarea><p class="'+(pg.requires_review?'warn':'ok')+'">'+(pg.requires_review?'تحتاج اعتماد OCR':'معتمدة')+'</p><button data-page="'+pg.id+'">اعتماد النص الظاهر</button></div>').join('');
pages.querySelectorAll('button[data-page]').forEach(b=>b.onclick=async()=>{let fd=new FormData();fd.append('corrected_text',document.getElementById('t'+b.dataset.page).value);let r=await fetch('/api/admin/lesson-pack-studio/jobs/'+id+'/pages/'+b.dataset.page+'/approve',{method:'POST',body:fd});let x=await r.json();action.textContent=r.ok?'تم اعتماد الصفحة'+(x.pack_invalidated?' — يلزم إعادة توليد الملزمة.':''):JSON.stringify(x.detail||x);await load()});
let vs=p.source_visuals||[];visuals.innerHTML=vs.length?vs.map(v=>{let b=v.bbox||{};let state=v.approved?'✅ معتمدة':v.rejected?'مستبعدة':'⏳ تحتاج مراجعة';return '<div class=visual-card><h3>'+esc(v.title||'شكل من المصدر')+'</h3><p class=muted>'+esc(v.description||'')+'</p><img src="/api/admin/lesson-pack-studio/jobs/'+id+'/source-visuals/'+encodeURIComponent(v.id)+'/preview"><p>'+state+' · ثقة الاكتشاف: '+Math.round(Number(v.confidence||0)*100)+'%</p><div class=crop-grid><label>X<input id="vx-'+v.id+'" type=number step=.001 min=0 max=1 value="'+Number(b.x||0).toFixed(3)+'"></label><label>Y<input id="vy-'+v.id+'" type=number step=.001 min=0 max=1 value="'+Number(b.y||0).toFixed(3)+'"></label><label>W<input id="vw-'+v.id+'" type=number step=.001 min=.03 max=1 value="'+Number(b.width||0).toFixed(3)+'"></label><label>H<input id="vh-'+v.id+'" type=number step=.001 min=.03 max=1 value="'+Number(b.height||0).toFixed(3)+'"></label></div><div class=action-row><button data-visual="'+esc(v.id)+'" data-act=approve>اعتماد القصاصة</button><button data-visual="'+esc(v.id)+'" data-act=reject>استبعاد</button></div></div>'}).join(''):'<p class=muted>لا توجد قصاصات مقترحة حتى الآن.</p>';
visuals.querySelectorAll('button[data-visual]').forEach(b=>b.onclick=()=>reviewVisual(b.dataset.visual,b.dataset.act));
studentPdf.href='/api/admin/lesson-pack-studio/jobs/'+id+'/export-pdf?edition=student';teacherPdf.href='/api/admin/lesson-pack-studio/jobs/'+id+'/export-pdf?edition=teacher';studentPdf.style.opacity=teacherPdf.style.opacity=data.teacher_approved?'1':'.45';studentPdf.style.pointerEvents=teacherPdf.style.pointerEvents=data.teacher_approved?'auto':'none';await refreshPreview(previewEdition,previewPage);}
async function reviewVisual(vid,act){let fd=new FormData();fd.append('action',act);if(act==='approve'){fd.append('x',document.getElementById('vx-'+vid).value);fd.append('y',document.getElementById('vy-'+vid).value);fd.append('width',document.getElementById('vw-'+vid).value);fd.append('height',document.getElementById('vh-'+vid).value)}let r=await fetch('/api/admin/lesson-pack-studio/jobs/'+id+'/source-visuals/'+encodeURIComponent(vid)+'/review',{method:'POST',body:fd});let x=await r.json();action.textContent=r.ok?(act==='approve'?'✅ تم اعتماد الصورة الأصلية. يلزم الاعتماد النهائي للملزمة.':'تم استبعاد القصاصة.'):JSON.stringify(x.detail||x);if(r.ok)invalidatePreview();await load()}
suggestVisuals.onclick=async()=>{action.textContent='جارٍ فحص صفحات المصدر بحثًا عن الأشكال المرتبطة بالشرح...';let r=await fetch('/api/admin/lesson-pack-studio/jobs/'+id+'/source-visuals/suggest',{method:'POST'});let x=await r.json();action.textContent=r.ok?'تم اقتراح '+x.count+' شكل/صورة من المصدر. راجع القصاصات قبل اعتمادها.':JSON.stringify(x.detail||x);if(r.ok)invalidatePreview();await load()};
function showPreviewPage(page=previewPage){previewPage=Math.max(1,Math.min(Number(page||1),previewTotal||1));pageCounter.textContent='صفحة '+previewPage+' من '+previewTotal+' · '+(previewEdition==='student'?'نسخة الطالب':'نسخة المدرس');pagePreview.src='/api/admin/lesson-pack-studio/jobs/'+id+'/preview-page/'+previewPage+'?edition='+encodeURIComponent(previewEdition)+'&v='+Date.now();openFullPreview.href='/api/admin/lesson-pack-studio/jobs/'+id+'/preview-pdf?edition='+encodeURIComponent(previewEdition);prevPage.disabled=previewPage<=1;nextPage.disabled=previewPage>=previewTotal}
async function refreshPreview(edition=previewEdition,page=previewPage){previewEdition=edition;let x=previewManifestCache[edition];if(!x){let r=await fetch('/api/admin/lesson-pack-studio/jobs/'+id+'/preview-manifest?edition='+encodeURIComponent(edition));x=await r.json();if(!r.ok){pageCounter.textContent='تعذر إنشاء المعاينة';action.textContent=JSON.stringify(x.detail||x);return}previewManifestCache[edition]=x}previewTotal=Number(x.page_count||0);showPreviewPage(page)}
studentPreview.onclick=()=>refreshPreview('student',1);
teacherPreview.onclick=()=>refreshPreview('teacher',1);
prevPage.onclick=()=>showPreviewPage(previewPage-1);
nextPage.onclick=()=>showPreviewPage(previewPage+1);
coverForm.addEventListener('submit',async e=>{e.preventDefault();let fd=new FormData(coverForm);let r=await fetch('/api/admin/lesson-pack-studio/jobs/'+id+'/cover',{method:'POST',body:fd});let x=await r.json();action.textContent=r.ok?'✅ تم حفظ بيانات الغلاف وتحديث المعاينة. يلزم الاعتماد النهائي للنسخة الجديدة.':JSON.stringify(x.detail||x);if(r.ok){invalidatePreview();previewPage=1;await load()}});
regen.onclick=async()=>{let fd=new FormData();fd.append('question_count','12');let r=await fetch('/api/admin/lesson-pack-studio/jobs/'+id+'/generate',{method:'POST',body:fd});let x=await r.json();action.textContent=r.ok?'تمت إعادة التوليد.':JSON.stringify(x.detail||x);if(r.ok)invalidatePreview();await load()};
sci.onclick=async()=>{let r=await fetch('/api/admin/lesson-pack-studio/jobs/'+id+'/scientific-review',{method:'POST'});let x=await r.json();action.textContent=r.ok?'اكتملت المراجعة العلمية: '+JSON.stringify(x.review):JSON.stringify(x.detail||x);await load()};
approve.onclick=async()=>{let fd=new FormData();fd.append('confirm_source_grounded',confirmSource.checked?'true':'false');fd.append('accept_reviewer_findings',acceptFindings.checked?'true':'false');fd.append('notes','Approved from Lesson Pack Studio workspace');let r=await fetch('/api/admin/lesson-pack-studio/jobs/'+id+'/approve',{method:'POST',body:fd});let x=await r.json();action.textContent=r.ok?'✅ تم الاعتماد النهائي. يمكن تنزيل نسختي PDF.':JSON.stringify(x.detail||x);await load()};load();
</script></main></html>"""


@app.get(
    "/admin/lesson-pack-studio/jobs/{job_id}/preview",
    response_class=HTMLResponse,
)
def lesson_pack_preview(job_id: str):
    return _preview_page(job_id)
