from fastapi.responses import HTMLResponse
from .main import app

BANK = r'''<!doctype html><html lang="ar" dir="rtl"><meta name="viewport" content="width=device-width,initial-scale=1"><title>بنك الأسئلة</title><style>
body{font-family:system-ui;background:#f5f7fb;margin:0;color:#172033}main{max-width:1400px;margin:auto;padding:16px}.box{background:#fff;border-radius:16px;padding:14px;margin:10px 0;box-shadow:0 3px 14px #0000000a}.top,.filters{display:flex;gap:8px;flex-wrap:wrap;align-items:center}input,select,button{padding:10px;border:1px solid #ccd2dd;border-radius:9px;font:inherit}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.card{background:#f8fafc;border-radius:12px;padding:12px}.grid{display:grid;grid-template-columns:1fr 340px;gap:12px}.q{padding:11px;border-bottom:1px solid #eee;cursor:pointer}.q:hover{background:#f8fafc}.tag{display:inline-block;padding:3px 7px;border-radius:999px;background:#eef2ff;font-size:12px;margin-left:4px}.muted{color:#667085;font-size:13px}.detail{white-space:pre-wrap;background:#f7f8fa;padding:10px;border-radius:8px}@media(max-width:900px){.grid{grid-template-columns:1fr}}
</style><main><h1>بنك الأسئلة</h1><div class="box top"><input id="key" type="password" placeholder="ADMIN_API_KEY"><button onclick="saveKey()">حفظ المفتاح</button><a href="/admin/workflow">مسار المراجعة</a><a href="/practice">واجهة الطالب</a><span id="msg"></span></div>
<div class="box"><div id="cards" class="cards"></div></div>
<div class="box filters"><select id="subject"><option value="">كل المواد</option></select><select id="grade"><option value="">كل الصفوف</option></select><select id="chapter"><option value="">كل الأبواب</option></select><select id="lesson"><option value="">كل الدروس</option></select><select id="qtype"><option value="">كل الأنواع</option><option value="mcq">اختيار من متعدد</option><option value="numeric">مسألة حسابية</option><option value="essay">مقالي</option><option value="unknown">غير مصنف</option></select><select id="difficulty"><option value="">كل الصعوبات</option><option value="easy">سهل</option><option value="medium">متوسط</option><option value="hard">صعب</option><option value="unclassified">غير مصنف</option></select><select id="state"><option value="">كل الحالات</option><option value="draft">مسودة</option><option value="cropped">تم القص</option><option value="reviewed">تمت المراجعة</option><option value="approved">معتمد</option></select><button onclick="loadQuestions()">تطبيق الفلاتر</button><button onclick="resetFilters()">مسح الفلاتر</button></div>
<div class="grid"><div class="box"><div id="count" class="muted"></div><div id="list"></div></div><div class="box"><h3>تفاصيل السؤال</h3><div id="detail" class="muted">اختر سؤالًا</div></div></div>
</main><script>
let lessons=[],academic={subjects:[],grades:[]};key.value=localStorage.pk||'';function h(){return {'X-Admin-Key':localStorage.pk||''}}function saveKey(){localStorage.pk=key.value;msg.textContent='تم الحفظ';loadAll()}
async function jf(u,o={}){let r=await fetch(u,o),x=null;try{x=await r.json()}catch(e){}if(!r.ok)throw new Error((x&&x.detail)||('HTTP '+r.status));return x}
async function loadAll(){try{academic=await jf('/api/academic/catalog');subject.innerHTML='<option value="">كل المواد</option>'+academic.subjects.map(x=>`<option value="${x.id}">${x.name_ar}</option>`).join('');grade.innerHTML='<option value="">كل الصفوف</option>'+academic.grades.map(x=>`<option value="${x.id}">${x.name_ar}</option>`).join('');lessons=await jf('/api/lessons');let chapters=[...new Set(lessons.map(x=>x.chapter))];chapter.innerHTML='<option value="">كل الأبواب</option>'+chapters.map(x=>`<option>${x}</option>`).join('');renderLessons();chapter.onchange=()=>{renderLessons();loadQuestions()};await loadStats();await loadQuestions()}catch(e){msg.textContent=e.message}}
function renderAcademicChildren(){let cv=curriculum.value?Number(curriculum.value):null;let terms=cv?catalog.terms.filter(x=>x.curriculum_version_id==cv):catalog.terms;term.innerHTML='<option value="">كل الترمات</option>'+terms.map(x=>`<option value="${x.id}">${x.name_ar}</option>`).join('');let tv=term.value?Number(term.value):null;let units=tv?catalog.units.filter(x=>x.term_id==tv):catalog.units;unit.innerHTML='<option value="">كل الوحدات</option>'+units.map(x=>`<option value="${x.id}">${x.title}</option>`).join('');renderLessons()}
function renderLessons(){let c=chapter.value;let arr=lessons.filter(x=>(!subject.value||x.subject_id==subject.value)&&(!grade.value||x.grade_level_id==grade.value)&&(!curriculum.value||x.curriculum_version_id==curriculum.value)&&(!term.value||x.term_id==term.value)&&(!unit.value||x.unit_id==unit.value)&&(!c||x.chapter==c));lesson.innerHTML='<option value="">كل الدروس</option>'+arr.map(x=>`<option value="${x.id}">${x.chapter} — ${x.title}</option>`).join('')}
async function loadStats(){let s=await jf('/api/question-stats',{headers:h()});let t=s.totals||{};cards.innerHTML=[['إجمالي الأسئلة',t.total||0],['معتمد',t.approved||0],['غير معتمد',t.unapproved||0],['سهل',t.easy||0],['متوسط',t.medium||0],['صعب',t.hard||0],['غير مصنف',t.unclassified||0]].map(([a,b])=>`<div class=card><div class=muted>${a}</div><h2>${b}</h2></div>`).join('')}
function params(){let p=new URLSearchParams({limit:'1000'});if(subject.value)p.set('subject_id',subject.value);if(grade.value)p.set('grade_level_id',grade.value);if(curriculum.value)p.set('curriculum_version_id',curriculum.value);if(term.value)p.set('term_id',term.value);if(unit.value)p.set('unit_id',unit.value);if(subject.value)p.set('subject_id',subject.value);if(grade.value)p.set('grade_level_id',grade.value);if(chapter.value)p.set('chapter',chapter.value);if(lesson.value)p.set('lesson_id',lesson.value);if(qtype.value)p.set('question_type',qtype.value);if(difficulty.value)p.set('difficulty',difficulty.value);if(state.value)p.set('workflow_state',state.value);return p}
async function loadQuestions(){try{let qs=await jf('/api/questions?'+params().toString());count.textContent=`عدد النتائج: ${qs.length}`;list.innerHTML=qs.length?qs.map(q=>`<div class=q onclick='showQ(${JSON.stringify(q.id)})'><b>#${q.id}</b> · ${q.chapter||'بدون باب'} · ${q.lesson_title||'بدون درس'}<br><span class=tag>${q.question_type}</span><span class=tag>${q.difficulty}</span><span class=tag>${q.workflow_state}</span><br>${String(q.text_verbatim).slice(0,180)}</div>`).join(''):'لا توجد نتائج';window._qs=qs}catch(e){msg.textContent=e.message}}
function showQ(id){let q=(window._qs||[]).find(x=>x.id==id);if(!q)return;detail.innerHTML=`<b>#${q.id}</b><p>${q.source_filename} — صفحة ${q.source_page||q.page}</p><p>${q.chapter||''} ${q.lesson_title||''}</p><p><span class=tag>${q.question_type}</span><span class=tag>${q.difficulty}</span><span class=tag>${q.workflow_state}</span></p><div class=detail>${esc(q.text_verbatim)}</div><p><a href="/admin/workflow">فتح في مسار المراجعة</a></p>`}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function resetFilters(){subject.value='';grade.value='';chapter.value='';renderLessons();qtype.value='';difficulty.value='';state.value='';loadQuestions()}loadAll();
</script></html>'''

@app.get('/admin/bank',response_class=HTMLResponse)
def admin_bank():
    return BANK
