from __future__ import annotations

from fastapi.responses import HTMLResponse

from .main import app


PAGE = r'''<!doctype html><html lang="ar" dir="rtl"><meta name="viewport" content="width=device-width,initial-scale=1"><title>المراجع العلمية</title><style>
*{box-sizing:border-box}body{margin:0;font-family:system-ui;background:#f5f7fb;color:#172033}main{max-width:1100px;margin:auto;padding:14px}.card{background:#fff;border:1px solid #e4e7ec;border-radius:14px;padding:14px;margin:10px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.row{display:flex;gap:8px;flex-wrap:wrap}input,select,button{font:inherit;padding:9px;border:1px solid #d0d5dd;border-radius:8px}input[type=text]{min-width:180px;flex:1}input[type=number]{width:92px}button{cursor:pointer}.primary{background:#101828;color:white}.muted{color:#667085}.ref{border-top:1px solid #eaecf0;padding:12px 0}.pill{display:inline-block;border-radius:999px;padding:3px 8px;background:#f2f4f7;font-size:12px}.ready{background:#ecfdf3;color:#027a48}.partial_ocr,.ocr_required{background:#fffaeb;color:#b54708}@media(max-width:760px){.grid{grid-template-columns:1fr}}
</style><main>
<div class=card><a href="/admin/lesson-studio">Lesson Studio</a> · <a href="/admin/lesson-studio/tools">أدوات الدرس</a> · <a href="/admin/dashboard">لوحة التحكم</a></div>
<div class="card grid"><div><h1>مكتبة المراجع العلمية</h1><p class=muted>ارفع مرجع PDF لكل مادة/صف. المرجع يُستخدم للتحقق وفهم نطاق الدروس ولا يغيّر شرح المدرس تلقائيًا.</p><p class=muted>لو المرجع ممسوح ضوئيًا، النظام يحفظ الأصل ويتيح OCR على دفعات صغيرة عبر Gemini مع الحفاظ على رقم الصفحة.</p></div><form id=form><input name=title type=text placeholder="اسم المرجع" required><div class=row><select name=subject required><option value=physics>فيزياء</option><option value=chemistry>كيمياء</option><option value=science>علوم</option></select><input name=grade_label type=text placeholder="الصف/المرحلة"><input name=academic_year type=text placeholder="العام الدراسي"></div><p><input name=file type=file accept="application/pdf" required></p><button class=primary>رفع وفهرسة المرجع</button><p id=msg class=muted></p></form></div>
<div class=card><div class=row><h2 style="flex:1">المراجع الحالية</h2><select id=filter><option value="">كل المواد</option><option value=physics>فيزياء</option><option value=chemistry>كيمياء</option><option value=science>علوم</option></select><button id=reload>تحديث</button></div><div id=list></div></div>
<script>
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function api(url,opt){let r=await fetch(url,opt);if(r.status===401){location.href='/admin/login';throw new Error('auth')}let x=await r.json().catch(()=>null);if(!r.ok)throw new Error(JSON.stringify(x?.detail||x||r.status));return x}
function ocrControls(r){if(r.ingestion_status==='ready')return '';let next=Math.max(1,(r.extracted_pages||0)+1);return `<div class=row style="margin-top:8px"><input id="start-${r.id}" type=number min=1 max="${r.page_count}" value="${next}"><select id="count-${r.id}"><option value=1>1 صفحة</option><option value=3 selected>3 صفحات</option><option value=5>5 صفحات</option></select><button onclick="runOcr('${r.id}')">OCR للصفحات</button></div><div id="ocr-${r.id}" class=muted></div>`}
async function load(){let s=$('#filter').value;let x=await api('/api/admin/lesson-studio/references'+(s?'?subject='+encodeURIComponent(s):''));$('#list').innerHTML=x.references.map(r=>`<div class=ref><b>${esc(r.title)}</b> <span class=pill>${esc(r.subject)}</span> <span class=pill>${esc(r.grade_label||'كل الصفوف')}</span> <span class="pill ${esc(r.ingestion_status)}">${esc(r.ingestion_status)}</span><div class=muted>${esc(r.filename)} · ${r.page_count} صفحة · مفهرس ${r.extracted_pages||0}/${r.page_count} · ${r.active?'نشط':'موقوف'}</div><button onclick="toggleRef('${r.id}',${!r.active})">${r.active?'إيقاف':'تفعيل'}</button>${ocrControls(r)}</div>`).join('')||'<p class=muted>لا توجد مراجع مضافة.</p>'}
async function toggleRef(id,active){let fd=new FormData();fd.append('active',String(active));await api('/api/admin/lesson-studio/references/'+id+'/active',{method:'POST',body:fd});load()}
async function runOcr(id){let fd=new FormData();fd.append('start_page',document.getElementById('start-'+id).value);fd.append('max_pages',document.getElementById('count-'+id).value);let box=document.getElementById('ocr-'+id);box.textContent='جارٍ OCR...';try{let x=await api('/api/admin/lesson-studio/references/'+id+'/ocr',{method:'POST',body:fd});box.textContent='تمت معالجة '+x.processed.length+' صفحة. الحالة: '+x.ingestion_status;setTimeout(load,500)}catch(e){box.textContent=e.message}}
$('#form').onsubmit=async e=>{e.preventDefault();let b=e.submitter;b.disabled=true;$('#msg').textContent='جارٍ الفهرسة...';try{let x=await api('/api/admin/lesson-studio/references',{method:'POST',body:new FormData(e.target)});if(x.duplicate){$('#msg').textContent='المرجع موجود بالفعل.'}else if(x.ingestion_status==='ready'){$('#msg').textContent='تم رفع وفهرسة المرجع بالكامل.'}else{$('#msg').textContent='تم حفظ المرجع. بعض الصفحات تحتاج OCR من القائمة بالأسفل.'}e.target.reset();load()}catch(err){$('#msg').textContent=err.message}finally{b.disabled=false}};$('#reload').onclick=load;$('#filter').onchange=load;load();
</script></main></html>'''


@app.get('/admin/lesson-studio/references', response_class=HTMLResponse)
def science_reference_library_page():
    return PAGE
